### ISSUE TITLE
Angular + Typescript generator?

### ISSUE THREAD

**Issue by pbolduc** [Azure/autorest#1013]
I was wondering if anyone know of work being done to create a generator for angular (1.x) service in TypeScript? I would expect this to be a 3rd party generator.

**Comment by amarzavery** [comment]
@pbolduc - We are currently generating node.js with Typescript definitions (*.d.ts) files. There is an ongoing work to make the generated node.js client isomorphic (to work in browser as well). However, we do not support generation of Angular.js based clients. 

We are open source and do accept contributions :).

**Comment by pbolduc** [comment]
Thanks @amarzavery.  The reason I posted this is to hopefully find someone that has already started on this work and I could contribute to.  The TypeScript definitions generated by the NodeJS generator would be a good place to start on an angular implementation.

**Comment by kenisteward** [comment]
Would it be better to work on the AutoRest side and get the gen from TS to Angular or just work directly under swagger-codegen ?  

I ask because it looks like there is at the very least a sample there already
https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-angular

**Comment by wing328** [comment]
@kenisteward  Swagger Codegen already supports Typescript (Node, Angular, Angular2, Fetch) API clients and there has been more than 80 PRs to enhance the Typescript client generator since the last stable release so please make sure you pull the latest master when generating Typescript API clients.

Disclaimer: I'm a top contributor to Swagger Codegen.

**Comment by kenisteward** [comment]
Thanks @wing328. I found that out when I did some more digging from the samples. Pretty happy about it :)

**Comment by olydis** [comment]
see #2452

**Comment by amarzavery** [comment]
@pbolduc - We have a new typescript based codegenerator that can be found here https://github.com/Azure/autorest.typescript. The generated code will work on the server as well as the browser.
