### ISSUE TITLE
Support overriding Swagger host with AutoRest command-line parameter

### ISSUE THREAD

**Issue by gitfool** [Azure/autorest#1036]
**Scenario**:
Using Swashbuckle to generate the Swagger.json used by AutoRest. I need to automatically modify the generated _proxy_ default host to be `localhost` (instead of whatever random machine was used to capture the Swagger.json at the time).

**Problem:**
Using a Swashbuckle DocumentFilter to modify host breaks the Swagger UI experience, so I should only override the default host name at proxy generation time, which would override the host specified in the Swagger.json, e.g.:

``` json
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "My Service"
  },
  "host": "myhost"
}
```

**Solution:**
Add a command-line parameter to AutoRest.exe to allow overriding the default host (to `localhost` in my scenario). Given this is possibly the only sensible default value, maybe don't even pass the host name, so just make it a switch?

**References:**
- [Swagger Spec](http://swagger.io/specification/)

**Comment by olydis** [comment]
@fearthecowboy Since this is easy with `directives`, how about adding this as a scenario to the samples and closing?

**Comment by olydis** [comment]
This may be a bit too corner-casey to get its own sample, especially since one can *easily* override the host name of the generated client using code: There's a constructor overload, or just set the `BaseUri` property.

Using a directive, one could override the host as follows:

```
from: swagger-document
where: $.host
set: localhost
```

More info on directives can be found in the docs, I'd recommend looking at example https://github.com/Azure/autorest/tree/master/Samples/3b-custom-transformations as a starting point.
