### ISSUE TITLE
Control C# client naming for models

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/autorest#1226]
I have an endpoint accepting a DTO looking like this:

```csharp
MyProject.Models.CreateUser
{
}
```

In the Swagger file, this generates a definition:

```json
"definitions": {
    "MyProject.Models.CreateUser": {
    }
}
```

When generating a C# client using AutoRest, with the -Namespace parameter set to MyProject, this will generate a DTO named `MyProject.Models.MyProjectModelsCreateUser`. In my opinion it doesn't make sense to re-use the namespace as part of the class name, when a namespace is specified on command line.

Is it possible to tell AutoRest not to use the full definition name? I've looked at https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md, but it doesn't look like custom naming is allowed on definitions.

**Comment by tbombach** [comment]
> In the Swagger file, this generates a definition:

How is this generated? (e.g. via Swashbuckle?) If so, I think it would probably make more sense for this type of fix to be in how Swashbuckle generates definition names, since having the DTO namespace in the definition name doesn't seem especially clean to me. 

You're correct, there's no custom naming option for definition model classes. We could consider adding an extension or something similar. It would probably depend on how the namespace gets in the definition name and how common that scenario is.

**Comment by ThomasArdal** [comment]
@tbombach generated with swashbuckle yes. I fixed the problem by removing the namespace from the definitions in the generated Swagger. But yeah a step for custom naming in Autorest sounds like a nice feature.

Anyway, I'll close this one since It's working as intended. Thank you very much.
