### ISSUE TITLE
[C#] FATAL Error generating client model: Value cannot be null.

### ISSUE THREAD

**Issue by ngzero** [Azure/autorest#1373]
```
Version 0.16.0
cmd>tools\AutoRest.exe -Input swagger.json -Namespace ecs.rest -OutputDirectory rest -CodeGenerator CSharp
```

Code generation failed.
AutoRest.exe -Input swagger.json -Namespace ecs.rest -OutputDirectory rest -CodeGenerator CSharp

> error: [FATAL] Error generating client model: Value cannot be null.
> Parameter name: key

There is no parameter with name key and I don't know if there should be somewhere a key???
I have attached the swagger.json as swagger.zip and the ECS folder with minimum files as ECS.zip. Inside the ECS folder there is a batch file with the command above and pause. You can extract it everywhere.

[swagger.zip](https://github.com/Azure/autorest/files/432428/swagger.zip)
[ECS.zip](https://github.com/Azure/autorest/files/432436/ECS.zip)

**Comment by amarzavery** [comment]
So I found the problem. We only support  "application/json" and "text/json" in produces and consumes. We do not support "application/vnd.github.v3+json" as mentioned in your swagger spec.
Once the produces was changed to "application/json" in the swagger spec then AutoRest generated the code without any exception.

It choked over [here](https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/SchemaBuilder.cs#L63)
```
Modeler.GeneratedTypes[serviceTypeName] = objectType; // serviceTypeName was null. The key of this dictionaly cannot be null.
```

The reason it reached this codepath because it thought the response schema returned by this operation is not a json object. Hence it tried to process this as a stream and failed over there.

In the condition over [here](https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/OperationBuilder.cs#L208) 
```
if (

    !(TryBuildResponse(methodName, response.Key.ToHttpStatusCode(), response.Value, method,

                            typesList, headerType) ||

      TryBuildStreamResponse(response.Key.ToHttpStatusCode(), response.Value, method, typesList, headerType) ||

       TryBuildEmptyResponse(methodName, response.Key.ToHttpStatusCode(), response.Value, method,

                              typesList, headerType)))
```
The TryBuildResponse returned false. Ideally that would have returned true if the consumes and produces were either of "application/json" or "text/json". But that wasn't the case. Hence it threw the above exception while processing the response as a stream where it clearly wasn't a stream.

Hope this helps :).

**Comment by ngzero** [comment]
Thank you very much, I've just changed the mime type of "consumes" and "produces" to application/json and autorest works very well now.

If you can, just answer me another question. The swagger specification lists several mime types, more than just application/json. Is there a reason why autorest doesn't know/support the others and only application/json and text/json?

**Comment by amarzavery** [comment]
"application/json" and "text/json" is the 80% scenario these days hence we made sure that it is implemented correctly. We are working on supporting "application/xml" and "text/xml" and it should be out pretty soon.

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' 💤 and we're going to review it during the post-1.0 planning cycle.

It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we must do before 1.0. 🏇 🏇 🏇

We'll make sure we pick this back up at that point. 🎉

(more to the point, when we get to the part about supporting other content types.)
