### ISSUE TITLE
AutoRest has to provide enough flexibility to bundle/unbundle at language level

### ISSUE THREAD

**Issue by kirthik** [Azure/autorest#1406]
There are the meeting notes/decisions from the Composite swagger meeting 
• If service team chooses to bundle all swagger specs of a Resource Provider into one package, this decision applies to all languages today. The main concern here is over how the tool is not providing enough flexibility to bundle/unbundle at language level. The experience that is correct in one language may not be correct for another language. So AutoRest should let the language generator choose the right behavior during generation.
o   For ex, if there is a composite swagger, we should be able to generate a single package in C# (by setting a flag or parameter on command line) but for GO we should be able to generate models per swagger file
• Also once the client library gets generated, it is not possible to map a model back to its swagger file when composite packaging happens. This information is lost. We should include swagger file name as part of namespace. Shared resources/base classes can be in a common namespace. If external json file is used for shared resources, it's URL can provide the namespace for shared classes.

**Comment by fearthecowboy** [comment]
>> "Composite swagger meeting" ? 

When was that?

>> The main concern here is over how the tool is not providing enough flexibility to bundle/unbundle at language level. The experience that is correct in one language may not be correct for another language. So AutoRest should let the language generator choose the right behavior during generation. 

Yes, the current implementation has a serious limitation with that.  The underlying issue with the current implementation is that by the time the language gets the code model, it's already been merged via the composite swagger modeler.

>> So AutoRest should let the language generator choose the right behavior during generation.

In order to do so, the code model would have to be given to the langauge generator in such a way that the generator could inspect the individual segments of the code model if necessary. 

>> Also once the client library gets generated, it is not possible to map a model back to its swagger file when composite packaging happens. This information is lost. We should include swagger file name as part of namespace. Shared resources/base classes can be in a common namespace. If external json file is used for shared resources, it's URL can provide the namespace for shared classes

Well, using swagger `file name` or `URL` isn't exactly the best way to model that, but yes, it should be possible to reference shared resources and have them generated appropriately.

The current `CompositeModeler` does actually generate multiple code models right now, but then as the last step, manually merges them together and throws away the bits.  I'm not fond of this behavior, and would like to replace it.

I have been thinking about a better way to accomplish that, where it generates multiple models, but then places a façade over top of the collection to give the `view` of a single model, but retain the ability for the language generator to still have access to independent models to do more specific things.

Thinking about that deeper, would be that we should be able to `extern` a reference to a model, which would make it easier to reference, rather than regenerate (or duplicate) common code.
