### ISSUE TITLE
Question: state of library

### ISSUE THREAD

**Issue by suddenelfilio** [Azure/autorest#1484]
Quick question regarding the state of autorest. Is there any future development planned? I noticed activity decline the last months. We are using the exe to generate all our client from swagger files. We are currently "stuck" on the 0.14 build as upgrading to 0.15-16 would mean a  refactoring of all the null to not-null for parameter changes that came after 0.14. 

Is there a successor for this library? or did it reach maturity as in no more development needed (although the issue count would suggest otherwise)

**Comment by fearthecowboy** [comment]
O_O.

Howdy, I'm Garrett, (aka @fearthecowboy ), the ever-vigilant Senior Open Source Developer leading the development on AutoRest. 

I, uh... I'm curious why you don't think there is an activity decline in the last few months? 

In the 133 days since I joined this team, we've had 352 commits, closed 139 issues and added several language generators to the mix. 

We publish a nightly build every night, which can always be grabbed with:

``` batch
# use NuGet 3.4 or newer!
NuGet.exe install autorest -source https://www.myget.org/F/autorest/api/v3/index.json -prerelease -outputdirectory "c:\autorest"
```
That being said, I'm curious about the actual problem that is blocking you from upgrading:
>> refactoring of all the null to not-null for parameter changes that came after 0.14.

To what specifically are you referring? I've done a lot of work recently with nullability in AutoRest (which should be making into a nightly build this week) 

If there is something that the latest binaries I can fix, lemme know ;D
