### ISSUE TITLE
NuGet package for 0.17.1 includes AutoRest.exe in the lib/net451 TFM

### ISSUE THREAD

**Issue by agc93** [Azure/autorest#1553]
Apologies if this is by design, but it's just changed with 0.17.1 for some reason.

The NuGet package for AutoRest 0.17.1 includes AutoRest.exe in the `lib/net451` folder/target, but without any of it's supporting DLLs, so cannot be run from that location. The 0.16.0 package did not include this.

![screenshot 73](https://cloud.githubusercontent.com/assets/1369269/19862577/ad58a810-9fdc-11e6-8083-ce40c3b2da5d.png)

Is there any reason to include the `.exe` here, as well as in the `tools/` target? The [nuspec itself](https://github.com/Azure/autorest/blob/6a1cab3d0ccf5aca762d8a0a5932c41c2b8c0030/src/core/AutoRest.Core/AutoRest.nuspec) doesn't seem to include this target either.

This change has broken the [Cake addin](https://github.com/agc93/Cake.AutoRest/issues/1) for AutoRest.

**Comment by fearthecowboy** [comment]
Ach!

The change is the result of switching to `dotnet-cli` tools  for compilation (a dependency we had to take for other reasons)... which means that package is created via the `dotnet pack` command, which isn't as flexible as the `nuget pack` command was. 

I wasn't going to fix that until the dotnet folks shipped their final tools, which I assume, will move back to nuget, since they're moving back to `.csproj` files for the project.

Lemme see if it's at all possible to just nuke the `lib` directory out of the package before publishing.

**Comment by fearthecowboy** [comment]
I've tweaked the build. I'm going to publish again (`0.17.2`) .. See if this works for you.

**Comment by fearthecowboy** [comment]
Make that `0.17.3` ... *sigh*

Confirmed that the `lib` folder is gone.

**Comment by agc93** [comment]
Awesome, thanks @fearthecowboy for the quick response!

I can also see the lib folder gone from 0.17.3.
