### ISSUE TITLE
New Rule: Check required properties of a model

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest#1589]
via @amarzavery 

While reviewing the webapp spec, I found that there are many models that have no required properties. After reading the description, at times it feels that some of them are required.

The thought process that I apply in my mind while reviewing something like this is as follows:
If the property is not readOnly: true then what happens if it is not provided? Does the server send back a 400 or applies a default? If the server applies a default then the default value should be described (unless this model is being referenced directly or in a nested fashion by an object that is a body parameter for a PATCH operation). If the server would send back a 400 that means the property was actually required.

- A property of a model should either be required or should have a default value (when optional) if and only if
   - it is not readOnly
   - it is a Primary Type {string, number, boolean, enum} (PrimaryType check in Autorest ServiceDefinition should be good enough check)
   - the model to which it belongs to and all the BaseModel Types of the model are not being referenced as a body parameter for any PATCH operation. (the last condition will also ensure that the body parameter for PATCH operation should not have any default values. If you implement this last condition as a separate rule then you just need to call the method for this Rule and be done for checking this last condition).

It would be nice if the spec author gets a warning of some kind about this. This will help us tremendously in data model validation using examples. If we catch issues like this early on then that would mean less breaking changes in the generated code/sdk.

**Comment by dsgouda** [comment]
If I have understood this correctly, what it would imply is that we force the author to mark every singly base data-type as a readonly. This might cause a fair bit of noise if the server returns a readonly composite object with a large number of base type fields.
@veronicagg thoughts?

**Comment by veronicagg** [comment]
@dsgouda I don't think every primary type should be read-only, I believe Garret is proposing to have the ones that are not read-only required (if some of the above conditions apply). If I understand correctly, the reasoning above implies that any property that's "optional" and not "required" should be used by the server in some way to process the request, therefore the statement that it returns either 400 or applies a default, though I'm not sure this is true all the time and I'm a bit worried we may interfere with some other rules (for example in cases where we advised to not marked "required" properties as "required" only because reusing models across operations could be more difficult - I know this may not be the ideal situation but it may conflict). If we wanted to try to pursue this, we could attempt an implementation (definintely as a warning) and run it in the repo to understand what the impact would be (how many are false positives versus real).

**Comment by dsgouda** [comment]
I think I have a better handle on this now. A few concerns I discussed with @veronicagg here
- Will generate a lot of noise for the existing specs in the repos
- There are many instances when authors have different model definitions for PUT request and response bodies. They will have to explicitly mark every request body parameter as required or provide a default value (in either case we can expect some resistance.)
We need to narrow down the applicability of this rule.

**Comment by veronicagg** [comment]
Closing issue, as it's been moved, see link above.
