### ISSUE TITLE
Child links and SDKs

### ISSUE THREAD

**Issue by kirthik** [Azure/autorest#1824]
Refer to https://github.com/Azure/azure-rest-api-specs/issues/328

**Comment by kirthik** [comment]
@colemickens , @lmazuel

**Comment by fearthecowboy** [comment]
After looking at the referenced issue -- I don't see what we can do in AutoRest. At best maybe a client runtime issue?

**Comment by colemickens** [comment]
@fearthecowboy It feels like something that needs to be done for all of the SDKs in a prescriptive manner, hence why I think I'd wanted it opened here.

This continues to be a serious pain point. We have hundred(s) of lines of code just to do resource ID composition and decomposition. It's amateurish to have to hack around the SDK everytime it's used for a non-trivial scenario. If this Issue is closed, I hope it can be championed elsewhere.
