### ISSUE TITLE
UpdatePet method from C# sample throws "Operation returned an invalid status code 'OK'" HttpOperationException

### ISSUE THREAD

**Issue by chuchuva** [Azure/autorest#1859]
Repro:

1. Download CSharp folder from https://github.com/Azure/autorest/tree/master/Samples/petstore/CSharp
2. Create new Console project with this code:

````
    var api = new SwaggerPetstore();
    api.UpdatePet(new Pet() {
         Id = 10,
         Name = "Sparky",
         PhotoUrls = new List<string> {"http://i.imgur.com/W4XRc43.jpg"}
    });
````

3. Run the program

Observe: HttpOperationException  is thrown. Message: Operation returned an invalid status code 'OK'.
Expected: no exception

If you examine the sample (auto-generated) code you will find this code in SwaggerPetstore.cs:

            if ((int)_statusCode != 405 && (int)_statusCode != 404 && (int)_statusCode != 400)
            {
                var ex = new HttpOperationException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                // ...
                throw ex;
            }

See https://github.com/Azure/autorest/blob/master/Samples/petstore/CSharp/SwaggerPetstore.cs#L455

Here is the HTTP request and response:

````
PUT http://petstore.swagger.io/v2/pet HTTP/1.1
User-Agent: FxVersion/4.6.1055.0 OSName/Windows_7_Enterprise OSVersion/6.1.7601 Petstore.SwaggerPetstore/1.0.0.0
Content-Type: application/json; charset=utf-8
Host: petstore.swagger.io
Content-Length: 99
Expect: 100-continue

{
  "id": 10,
  "name": "Sparky",
  "photoUrls": [
    "http://i.imgur.com/W4XRc43.jpg"
  ]
}


HTTP/1.1 200 OK
Date: Tue, 21 Feb 2017 03:11:48 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Access-Control-Allow-Headers: Content-Type, api_key, Authorization
Content-Type: application/json
Connection: close
Server: Jetty(9.2.9.v20150224)

{"id":10,"name":"Sparky","photoUrls":["http://i.imgur.com/W4XRc43.jpg"],"tags":[]}
````

**Comment by amarzavery** [comment]
The Petstore swagger is wrong on several counts.
As per the [Open API Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object)
> The Responses Object `MUST` contain at least one response code, and it `SHOULD` be the response for a **successful operation call**.

However, the `UpdatePet` operation in [Petstore swagger](http://petstore.swagger.io/v2/swagger.json) specifies only the negative response codes, which is grossly incorrect.

**Comment by chuchuva** [comment]
Open API team [thinks otherwise](https://github.com/OAI/OpenAPI-Specification/issues/898#issuecomment-281238113):

> It probably should [200 response be included], in fact in the V3 spec, it explicitly states that the successful response SHOULD be included. However, it isn't a MUST and AutoREST shouldn't assume that it will be there.

**Comment by webron** [comment]
I'll add the comment here as well - in that regard, the petstore sample is *not* wrong. Even though we've made mistakes in the spec, the `SHOULD` word was picked there on purpose. We were trying to encourage people to include a successful response but not mandate.

In fact, for a brief moment, we almost removed that recommendation at all for 3.0.

As a code generation tool, autorest (which is a great tool), should thrive to be robust and deal with these things. You shouldn't expect people to document their APIs entirely, because people are people. What if the API ends up returning a response that's not documented? Will that make the code explode? I hope not. 

While we SHOULD (see what I did there?) improve the sample itself, autorest SHOULD NOT fail for these use cases.
