### ISSUE TITLE
Returning a NULL results in a NoContent exception.

### ISSUE THREAD

**Issue by Serjster** [Azure/autorest#1876]
Currently when we want to return a null result, for example a nullable DateTime, the client throws a NoContent exception. The 2 work-arounds right now is to either return a NotFound() or to create a DTO that has a single nullable DateTime property. So this is not a show stopper, but I should be able to just return a null and receive a null on the other side.

**Comment by olydis** [comment]
I know this issue is super old, sorry for not getting back earlier. We do have cases/tests where empty responses are not throwing an exception (but deserialize to `null`) so I suspect the problem is to some extent specific to your case. If this is still an issue in recent releases of AutoRest, could you please provide an example Swagger for us to repro the issue?

**Comment by EngineerCoding** [comment]
I am having issues with this as well, and this is caused because the rest client checks specifically for status code 2o, which means that 204 gets denied hard.
