### ISSUE TITLE
ARMResourcePropertiesBag: update rule, reporting many false positives

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1967]
@ravbhatnagar Could you clarify the spec for this rule? We believe the current implementation is too strict. 

Check DataFactory swagger for this rule, this rule maybe too strict. We may only need to validate that the top level properties in the property bag of a "Resource" like object, should not have id, name, type, location, tags. It is ok if the model has a property named id one level down than that. For example "StorageAcount.properties.foo.id" is ok but "StorageAcount.properties.id" is not .

Category: RPC Violation
Severity: Error

**Comment by veronicagg** [comment]
it's also flagging "properties" as not allowed - see https://github.com/Azure/azure-rest-api-specs/issues/995

**Comment by ravbhatnagar** [comment]
@veronicagg - 2 rules are in question here- one is the allowed set of properties at the top level, second is that the top level properties should not be repeated inside properties.
For second - we should definitely exclude "properties" from the check. Also lets just check only one level deep and so StorageAccount.properties.id is a violation but StorageAccount.properties.foo.id is not. 

For first - since its checking the allowed set of top level properties, "properties" should be a part of the check. 

One thing to note here is that these properties can change. For example- ARM may add another top level property soon. So how can we minimize the impact on the code for the rule to change. Can the rule get the allowed set of properties from common definitions or some other config file?

**Comment by veronicagg** [comment]
@ravbhatnagar thanks! Could you confirm this applies to "Resource" (and not only to "Tracked Resource")?

**Comment by ravbhatnagar** [comment]
@veronicagg - Yes, this applies to the Resource
