### ISSUE TITLE
[Potential Issue] Resource ID pattern may include "provider" word twice

### ISSUE THREAD

**Issue by vishrutshah** [Azure/autorest#2126]
Example Path
```
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProvider}/{resourceType}/{resourceName}/providers/Microsoft.ResourceHealth/availabilityStatuses/current
```
Reference RP: `arm-resourcehealth` 
https://github.com/rajithanitc/azure-rest-api-specs-pr/blob/d2ab128a64bfbc6276d3f7c53a3bba3dd23a23fc/arm-resourcehealth/2015-01-01/swagger/resourcehealth.json

I believe this is something called "extension resource providers" but we may want to look into whether our rules based on some regex works as expected or not.

Reference: [resourceProviderPathPattern ](https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs#L25) [ResourcePathPattern ](https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs#L23)

CC:
@veronicagg @dsgouda @sarangan12

**Comment by dsgouda** [comment]
We already have a validation rule [here](https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/Validation/ProvidersPathValidation.cs#L15) that flags all paths that do not adhere to the ```resourceProviderPath``` regex that we use. I'd start with finding all RPs that violate this rule and which ones we should be relaxing our rules for, and start working our way towards the more complex path-regex based validation rules.

**Comment by vishrutshah** [comment]
@dsgouda As far as I know that is a valid path for RP but we can dig deeper into it.

**Comment by sarangan12** [comment]
Here is the deal: The Tenant Resources should be processed for ListByResourceGroup/ListBySubscriptionId. Get Operation rule is fine.  We have seperate issue for that: https://github.com/Azure/autorest/issues/2170 & https://github.com/Azure/autorest/issues/1840. So, the issue with tenant level resources are already handle among those issues and this issue seems to be redundant. So, I am closing this issue now. If you still have any concerns, feel free to reopen this issue
