### ISSUE TITLE
[Linter] Review rules about naming conventions to be consistent

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#2149]
We should review our current rules related to naming conventions, to be consistent and potentially more accurate, and evaluate whether each should be warning or error.

**Comment by dsgouda** [comment]
I'm restricting the scope to list-related rules here.
1. For any x-ms-pageable operation, the operationId should be of the form “*_list*” to which some valid arguments have been raised [here](https://github.com/Azure/autorest/issues/1955#issuecomment-292009079). Further there is inconsistency like “Operations_List” and “ListOperations” which we need to resolve.
In the interim, there is also an issue opened [here](https://github.com/Azure/autorest/issues/2138) for correcting the error message displayed for this error.

2.	Naming list Operations for Tracked resources
      a.	A list operation should be “*_list” or “*_listBySubscriptionId” 
      b.	A list operation should be “*_listByResourceGroup”
      c.	A list operation should be “*_listByImmediateParent”

For rule a and b we simply evaluate all the tracked resources found in the spec and check if operations indicated by a. and b. exist. For Example, if “DataFactory” was a tracked resource, we would 
check for every operationId in the spec that ends with “*_list*” and check if it returns and array of “DataFactory”. We are not checking/suggesting the operationId itself here, if we had to how should we go about it?

For rule c however, there are a fair bit of complications. If I understood @sarangan12  and @ravbhatnagar we need to figure out the immediate parent resource of a resource in from the url, and then we 
construct a string like “Resource_listByParentResource” (I believe we do some further execution to ensure we have correctly figured out the parent resource. @Sarangan can you explain this in 
layman terms). I would recommend turning this into a warning since I do feel the logic is involved is quite complicated. 

3. There is also an existing rule [here](https://github.com/Azure/autorest/blob/eaf9a9203736e71903d16785d9f8310dce60d5bb/src/modeler/AutoRest.Swagger/Validation/ListByOperationsValidation.cs) which works with an outdated version of resource and must be removed. There is a PR removing this rule [here](https://github.com/Azure/autorest/pull/2144)

Please feel free to add any other issues here that I might have missed.
@ravbhatnagar @kirthik we'd like to know your thoughts on problems outlined under points 1 and 2.

@veronicagg FYI

**Comment by iouri-s** [comment]
Names a and b inconsistent

THey should either be 
listBySubscriptionId and listByResourceGroupName

or listBySubscription and listByResourceGroup

If we take a broader perspective, the use of "by" is questionable as well. 
To list resources by resource group, means to list all resources, organized/grouped by resource group (see for example "Gun homicides and gun ownership listed by country"  - https://www.theguardian.com/news/datablog/2012/jul/22/gun-homicides-ownership-world-list)

A better name would be List(In)Subscription or List(In)ResourceGroup.

**Comment by veronicagg** [comment]
@sarangan12 , @dsgouda is this issue still valid? We've fixed several things on naming rules and are less strict on the naming,, so I wonder if we could just close this issue.

**Comment by dsgouda** [comment]
Points 1 and 3 have been addressed. @sarangan12 can you check if we have addressed point 2.

**Comment by dsgouda** [comment]
Talked to @sarangan12  offline and I think the concerns I had raised have been addressed.
