### ISSUE TITLE
[linter] Potential issue with OperationIdNounConflictingModelNames

### ISSUE THREAD

**Issue by dsgouda** [Azure/autorest#2214]
While reviewing https://github.com/Azure/azure-rest-api-specs-pr/pull/66/files I noticed we are flagging ```BatchAccount``` as a potential conflicting name with model definitions. However, looking at the operationIds ```BatchAccount_Create```/```BatchAccount_Update``` makes a lot more semantic sense than saying ```BatchAccounts_Create```/```BatchAccounts_Update``` which we tend to recommend. 
I am not sure if we are really adding any value here. 
Tagging @veronicagg

**Comment by veronicagg** [comment]
@dsgouda The consequence of having conflicting name is that in the generated code, BatchAccount_Create will end up as "BatchAccountOperations" class, with a "create" operation. AutoRest needs to disambiguate, so it adds "Operations" to the class. For reference see: https://github.com/Azure/azure-sdk-for-net/blob/vs17Dev/src/SDKs/Batch/Management/Management.Batch/Generated/BatchAccountOperations.cs 
With the linter warning, we're trying to help the user disambiguate consciously. I don't think we have a doc describing this, but we should. 
In the particular case that you referred above though, since we have SDKs that shipped that way, I understand that it'd be better to not follow the guidance from the warning, as it's just a naming detail that would break consumers.
Let me know if there's something else you'd like to discuss/do with this issue, if not, feel free to close it.
Thanks!

**Comment by dsgouda** [comment]
Thanks for clearing this again! 😄
