### ISSUE TITLE
Unicode problems on Jenkins (causing `tox` to fail when parsing ENV variables with Emojis)

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2217]
See https://github.com/Azure/autorest/pull/2216.

It looks to me like the emoji in the *PR description* fails the Python tests. But only on Jenkins. What I'm most confused about is how that description even ends up in any test!?

**Comment by olydis** [comment]
@lmazuel Could you look into that whenever you have some spare time? :-) This is not critical (now that I'm aware of that issue), it just seriously confused me and could potentially confuse people in the future

**Comment by lmazuel** [comment]
@olydis Looking at Google, it seams Tox is trying to parse all environment variables. This means that it's likely because the shell Jenkins uses is ASCII or POSIX pr CP1252, and the automatic env variable from Jenkins (with latest comment, etc.) are using UTF-8.

Best fix is to declare the shell to be UTF8. Less better fix is to manually "destroy" env variable that Tox does not need. Or be less happy and don't use fireworks in comments :)

**Comment by olydis** [comment]
@lmazuel hehe, thanks for investigating! We'll look into the encoding but pretending to be less happy is also an option 😄 🎉

**Comment by olydis** [comment]
No longer an issue after everything is split.
