### ISSUE TITLE
Linter should support a configuration file for Swaggers

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#2349]
The linter should support a configuration file that lives either beside each swagger file (or in some global location, or as an annotation within the Swagger file?) which allows teams to opt out of certain linter rules.

**I envision these features:**
1. Opt out of a rule entirely for the whole file
2. Opt out of a rule but only for a particular occurrence of a violation, identified by the "path" to the violation (i.e. models/FooBarBaz/property("qux") or however you want to describe the path).
3. Linter could have a mode where it ignores the opt-outs, and the bot/CI can run in both modes and report both new errors/warnings and opted out errors/warnings.

**This has a lot of advantages:**
1. Some teams (like mine) have a REST API that is years old. Some of the new rules (Boolean vs Enum, etc) are great and we try to follow them for new properties, but we can't just make huge breaking changes across the whole API, so the old stuff that violates the rules would be great to opt out of seeing since we're not going to change it.
2. It would allow a relatively easy way for teams with data plane APIs to opt out of all of the ARM junk which doesn't apply (might want an opt out of category too so you could just opt out of all the arm specific stuff immediately).
3. Since it's in a config file, teams can't just willy nilly ignore any errors they like, you would have to accept the PR with the config file (which you could review and question why they are opting out of certain things).
4. Gives teams with existing Swaggers who want to follow all of the rules but can't yet (because it takes server changes or they are waiting to make a big breaking change and follow them) a way to incrementally improve linter pass rate while at the same time staying "clean"
5. Because of 4 above, you could probably enforce the linter as an actual CI gate as opposed to just informational like now, and just ask teams submitting new Swagger files to just add a linter config file opting them out of their existing errors (provide a tool to generate it for them is bonus points).

This also follows the paradigm of pretty much every linter out there - not every rule applies to every case and most linting tools allow for configuration of the rules.

**Comment by olydis** [comment]
@matthchr I can happily announce that features 1 and 2 already exists 😉 see our Samples [2a](https://github.com/Azure/autorest/tree/master/Samples/2a-validation) and [2b](https://github.com/Azure/autorest/tree/master/Samples/2b-suppressions), more detailed documentation will follow once we move the swagger repo and CI to configuration files (July). E.g. you can actually leave out details like `where`, `suppress` entire categories of errors, or give lists instead of single values for `suppress`, `from` and `where`.

Regarding 3, there is currently no "opt-out" mode, however one *can* (and we should probably make that the guideline!) add [guards](https://raw.githubusercontent.com/Azure/autorest/master/Samples/3c-guards/readme.md) around the suppression section such that suppressions become conditional in the first place. For example, I could think of either `$(suppressions)` to raise awareness that things are getting suppressed or `!$(no-suppressions)` to require work for opting out.

Regarding the data plane concerns: Rules are categorized between data-plane and ARM as we speak, so the ARM rules won't run on data-plane Swaggers in the first place (no suppressions required). All the points you give make perfect sense, seems like we're on the same page! 🙂

**Comment by matthchr** [comment]
Nice -- is the Readme.md the actual suppression file as well (i.e. the linter parses the Readme)?

Should I add one of these in the existing PR I have open or wait for you guys to do your thing in July?

**Comment by olydis** [comment]
AutoRest parses the configuration file (yes, the suppressions go right in there). The linter itself is just an AutoRest plugin while the VSCode extension "linter" uses AutoRest. If you want suppressions now, i.e. ignoring messages until July is too much of a pain, feel free to add the file (you should already find some, other RPs have moved to config files themselves too). Otherwise, I would wait and simply add the suppressions to the file you will see in July (things are assembled in the `reorg` branch)

**Comment by fearthecowboy** [comment]
Yes, the readme.md is the actual suppression file (it's all *configuration*) -- take a peek at the `reorg` branch in `azure-rest-api-specs` repo and you'll see the we've started creating `readme.md` files for absolutely everything.

> **Interesting Fact** : the whole point behind the `readme.md` configuration file is to capture all the configuration in a single location, and ensure that we (soon) get 100% the same experience at the command line, in VSCode and in CI. 

If you want to jump the gun, you can create a `readme.md` file and include it with your PR, and we'll make sure we merge that in with our reorg branch.

**Comment by matthchr** [comment]
Is it necessary to link to the commit hash of the Swagger file being discussed?

It's hard to do that when I don't have a commit hash yet since my Swagger file hasn't been merged. If I omit that part is it implied that the readme applies to the adjacent Swagger?

**Comment by fearthecowboy** [comment]
It should work perfectly fine with relative paths.

**Comment by olydis** [comment]
All this should work now. Please reopen if this is not the case.
