### ISSUE TITLE
x-ms-paths documentation is incomplete

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#2440]
The following needs to also be included in the documentation:
* the query parameter included in the path **is not actually used anywhere** it is only for disambiguation of paths entries. What this means, from a practical perspective, is that you must still include the query parameter in the `parameters` block **even if the operation is a constant value**
* You must have a basic path without query parameters in the swagger `paths` block. All query param disambiguation must "overload" that basic path.

**Comment by olydis** [comment]
tracked by #1770, should be able to address this today

**Comment by olydis** [comment]
@begoldsm Note that the docs actually say

> To overcome this limitation an "x-ms-paths" extension was introduced parallel to "paths". URLs under "x-ms-paths" are allowed to have query parameters for disambiguation, however they are removed during model parsing.

I'll gladly add your practical illustration, though!

> You must have a basic path without query parameters in the swagger paths block. All query param disambiguation must "overload" that basic path.

Well, not really/technically, it's just what we suggest since that way the Swagger is as standard as possible... having the "basic path" in the `paths` block instead of `x-ms-paths` means one more method is visible to standard compliant tools...
