### ISSUE TITLE
Node.js Generator 2.0 doesn't generate async & pageable operations

### ISSUE THREAD

**Issue by number213** [Azure/autorest#2485]
I tried versions `1.2.0`, `1.2.1`, `1.2.2`, all of them skip on generating async (that start with `begin`) and pageable (e.g. `listNext`) operations which would be a breaking change in SDK.
Rolling back to `1.1.0` helped but that required creating new composite swagger because swagger repo uses markdown configs now.

Autorest specs:
```
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
  Build Information
  Autorest Bootstrapper :  1.2.2
  NetCore framework :      1.0.5
  Latest Core Installed :  1.2.2
  Requested Core Version : <none>
Installed versions of AutoRest :

  1.2.2
  1.2.1
  1.2.0
  1.1.0
  1.0.1
```

**Comment by fearthecowboy** [comment]
Can you show me the commandline/configuration and swagger files?

There should be no difference between 1.1* and 1.2* in code generation.

**Comment by number213** [comment]
Swagger: https://github.com/number213/azure-rest-api-specs/tree/lb-update/specification/network/resource-manager

Didn't work (invoked from directory with md-file):
`autorest --tag=package-2017-06 --output-folder=%out% --license-header=MICROSOFT_MIT --nodejs`

Worked:
`autorest --version=1.1.0 -Modeler CompositeSwagger -CodeGenerator Azure.NodeJS -Input %PathToCompositeSwagger% -outputDirectory %NodeOut% -Header MICROSOFT_MIT`

**Comment by fearthecowboy** [comment]
Oh, it's `nodejs` ... @balajikris and/or @amarzavery  -- was there changes to the `nodejs` generator that would cause this?

**Comment by balajikris** [comment]
I don't remember any changes around this area, perhaps @amarzavery might.. Or will look at `git history` in a bit.. But I wonder if this is because of a missing argument `--azure-arm`. @number213 's command with md-file is invoking the generic template and not the azure specific one, whereas his other command invokes `Azure.NodeJs`.. That's one diff I spot by looking at the command, but if that isn't it then have to debug.

**Comment by fearthecowboy** [comment]
ah yes -- @number213  -- you should add `--azure-arm: true` to the configuration file (after the line `tag: package-2017-06` ) 

``` yaml 
title: NetworkManagementClient
description: Network Client
openapi-type: arm
tag: package-2017-06
azure-arm:true # add this line
```

**Comment by balajikris** [comment]
@fearthecowboy : what's the recommended practice here? Have it in the config versus pass in as command line argument? I don't think most other specs specify this either, but when we're generating code for publishing, we invoke autorest with appropriate arguments, so we get it right in our script.

There are some services (service fabric) for eg. who requested we use the generic version. This logic is now in our script as to how to control the shape of the generated api.. Do you recommend this be pushed down to the config files in the spec?

**Comment by number213** [comment]
`--azure-arm` did the trick, thanks!

**Comment by fearthecowboy** [comment]
@balajikris - the long term goal is to concentrate as much of the configuration into a single location (the `readme.md` config file) so that the generation command lines get as simple as possible, and we have all of the generation information available in a single location. If we can cut down on the amount of tangential automation, we're doing everyone a favor.

Immediately, it's not *critical* that it's all in there, but that should be our goal over time.
