### ISSUE TITLE
Compiler warning CS1573 for models with enum values + other parameters

### ISSUE THREAD

**Issue by seth-capistron** [Azure/autorest#2526]
I'm having a problem where some of the generated model files are resulting in the [CS1573 compiler warning](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1573). Since the project containing the models has Documentation enabled, this is resulting in my build failing. I believe I've narrowed it down to the following case, given a Swagger doc like this...

```
"Test.Model.HistoryItemV1": {
    "type": "object",
    "properties": {
		"id": {
			"format": "uuid",
			"type": "string"
		},
		"approvalType": {
			"enum": [
				"Invalid",
				"NoApprovalRequired",
				"AutoApproval",
				"SingleApproverRequired",
				"MultipleApproversRequired"
			],
			"type": "string"
		}
	}
}
```

Will generate a model constructor like this...

>         /// <summary>
>         /// Initializes a new instance of the
>         /// TestModelHistoryItemV1
>         /// class.
>         /// </summary>
>         /// <param name="approvalType">Possible values include: 'Invalid',
>         /// 'NoApprovalRequired', 'AutoApproval', 'SingleApproverRequired',
>         /// 'MultipleApproversRequired'</param>
>         public TestModelHistoryItemV1(System.Guid? id = default(System.Guid?), string approvalType = default(string))
>         {
>             Id = id;
>             ApprovalType = approvalType;
>             CustomInit();
>         }

The problem is that CS1573 complains because approvalType has a param tag, but id does not. If I add an empty param tag for id, then the compiler error goes away. This is the behavior I would expect by default from AutoRest.

**Comment by olydis** [comment]
Documentation in the Swagger becomes documentation in generated code. So all you have to do is add a `description` to your `id` property and there should appear a corresponding XML tag.

**Comment by seth-capistron** [comment]
Not sure that this solves my problem. When I look at the original model file in C#, I see that all the properties have <summary> documentation. Although, I don't see any of those summary strings being populated in the Swagger json file. Could this be an issue with how we are generating the Swagger doc?

Regardless though... this implies that if I have a model with two parameters, one being an enum and the other being a string, the only way to avoid CS1573 is to add a description to all non-enum properties. This seems broken, no? Why should description be required at all?

Why wouldn't AutoRest have logic to say... if I add a <param> tag for one attribute, then I better make sure I add (at the very least) empty tags for all the other attributes? Otherwise, the consumer of the code is hit with CS1573.

**Comment by olydis** [comment]
> Although, I don't see any of those summary strings being populated in the Swagger json file. Could this be an issue with how we are generating the Swagger doc?

Maybe it is, please check if the property has it's documentation in the Swagger.

> Regardless though... this implies that if I have a model with two parameters, one being an enum and the other being a string, the only way to avoid CS1573 is to add a description to all non-enum properties. This seems broken, no? Why should description be required at all?

I actually think that makes perfect sense! CS1573 warns about missing documentation, which really just reflects that the Swagger... is missing documentation. The "missingness" is merely forwarded from Swagger to C# (you're lucky with enums since AutoRest *appends* documentation to enums -- which in your case ends up to be the *only* documentation). In other words: If missing documentation is no issue for you, just suppress CS1573, otherwise add the documentation (or make the tool do that). Why should AutoRest make warnings about missing documentation disappear if the documentation is actually missing?

**Comment by seth-capistron** [comment]
> Why should AutoRest make warnings about missing documentation disappear if the documentation is actually missing?

Because it is AutoRest's cleverness that is causing the warnings in the first place. The description field for properties in the Swagger doc is optional. How do I know this? Because if I have an object that has two string properties and neither has a description, AutoRest will generate a C# class that doesn't produce any warnings.

It's only when one of the properties is an enum that AutoRest tries to be clever and insert the possible enum values into the <param> tag. This is what creates a warning. The only difference between the two cases is that AutoRest is trying to be clever in the second case.

**Comment by olydis** [comment]
Maybe I'm not getting something essential, but as far as I can tell, it's really just that one description is present, the other is not. So sure, in your case it's because AutoRest appends stuff to an enum property description, but in general, I expect the same behavior if the Swagger author only provides documentation for one property. That C# doesn't complain if *no* parameters are documented is weird, but apparently what they decided to do, so essentially your lucky.

Still I don't get the main ask: You apparently don't want to put documentation in your Swagger, the C# compiler triggers a warning that is related to missing documentation, so why not mute it or add the documentation? What is it you would AutoRest expect to do? Adding empty tags, as you suggest, would be a cheaty way of muting the warning (since really, there's *still no documentation*)!

Can you explain your scenario better? If you don't care about documentation, suppress CS1573, otherwise add documentation. Anything I can do in AutoRest would mean shutting up a warning that raises a perfectly valid concern (that IMO should also be raised if no properties have documentation). Why? Our main design goal is to generate code that is of use to customers. Injecting empty documentation tags to mute a warning that can raise developer awareness about missing documentation is contradicting that design goal. At the same time, developers who know what they're doing can add one suppression to their project and CS1573 is muted. I'll gladly make changes to code generation, but which changes do you propose and who benefits from them?

**Comment by olydis** [comment]
For the record, the CLI parameter that injects dummy descriptions:
```
--directive='{ transform: ''$.description=$.description || `The ${$path[3]} property.`'', from: swagger-document, where: $.definitions.*.properties.* }'
```

@seth-capistron Feel free to reopen if the above does not work.
