### ISSUE TITLE
Parameter definitions defined outside of an endpoint results in client generating methods missing parameters.

### ISSUE THREAD

**Issue by RemyArmstro** [Azure/autorest#2536]
If you generate a client against a Swagger doc that has parameters defined outside of the "paths" section in the "parameters" section, and then you refer to those parameters using references in the individual path parameters collection, the generated client does not have those parameters in the methods.

ex that would cause bad generation: 
`"paths": {
    "/testEndpoint/": {
      "get": {
        "description": "Test endpoint.",
        "operationId": "GetTest",
        "parameters": [
          { "$ref": "#/parameters/testParameter" },...`

vs ex that works:

`  "/testEndpoint/": {
      "get": {
        "description": "Test endpoint.",
        "operationId": "GetTest",
        "parameters": [
         {
            "description": "test integer",
            "format": "int32",
            "in": "path",
            "name": "test_id",
            "required": true,
            "type": "integer"
          },...`

Note: This was using the C# generated client.  Haven't tried the others.

**Comment by fearthecowboy** [comment]
AutoRest by default assumes that globally referenced parameters are 'global' to the generated client.

In the parameter definition, use `"x-ms-parameter-location":"method"` to have the parameter added to the method instead of the class.

example: https://github.com/Azure/autorest/blob/f354aa749a3337736a8bfc9474ccba1183b8693a/src/autorest-core/test/resources/validation-options/specjsons/vaultusages.json#L182

**Comment by RemyArmstro** [comment]
Thank you.
