### ISSUE TITLE
autorest requires .net core

### ISSUE THREAD

**Issue by vhe1** [Azure/autorest#2553]
Hi!
I just wanted to update from 0.17.3 to the latest stable.
This doesn't work because we use the full .net framework.
What's going on? Is there another package for normal projects?
What would be the last package that works?

Also, it doesn't install in VS 2015 because it requires a new package manager. But we already have the newest package manager.

We have a problem with a generated c# client not compiling (type error in a `??` expression) and are a bit at a loss right now.

**Comment by olydis** [comment]
As you indicated in the title, AutoRest only requires dotnet core instead of the full framework now (next release will run on dotnet core 2.0) in order to run consistently on all platforms. What do you mean with "normal projects"? AutoRest is distributed through `npm` now.

Reading between the lines, it sounds like you are using and invoking AutoRest from within a project, not just using it as a command line tool to generate code, is that correct? The AutoRest core is written in NodeJS, exposes an API there, however that may not help you if you wanna invoke AutoRest from a .Net application. In that scenario, I guess the easiest way right now is to invoke an AutoRest process.

**Comment by vhe1** [comment]
> AutoRest is distributed through npm now.
So, what about the autorest nuget package then? I don't understand it.

**Comment by olydis** [comment]
Pretty sure that is just a wrapper around the npm package and possibly NodeJS, /cc @fearthecowboy

**Comment by fearthecowboy** [comment]
The autorest package in nuget is a tool package, not a library package. Unfortunately, nuget doesn't make the distinction clear at this point. 

The nuget package is indeed just a rollup of the nodejs executable, and the core autorest package in a single package.  

It's not a consumable library.

**Comment by olydis** [comment]
Closing, assuming that questions are answered. Please reopen or keep posting if you have any more questions/issues about this!
