### ISSUE TITLE
Multiple allOf references

### ISSUE THREAD

**Issue by dco123** [Azure/autorest#2657]
In #1180 it is mentioned that multiple inheritance may be addressed in future using interfaces - I'm just wondering what the status of that is? Are there still plans to support multiple allOf ref's through interfaces? Only supporting polymorphism on schema's with one allof ref causes issues for us because that doesn't logically apply to some of our models.

Thanks

**Comment by olydis** [comment]
@dco123 Still planned, but not on the top of the list of our priorities. Most importantly, it would be a breaking change compared to how we generated things in the past. Due to our commitment to not break our customers, we would have to maintain two ways to handle `allOf` for a good while.

Still, it is the long term goal to do this (remodel polymorphism in general, more things are impossible with the current modelling), but I can't estimate when that will happen.

**Comment by dco123** [comment]
Ok, thanks for the update

**Comment by raveeshupahuja** [comment]
any update on this?
