### ISSUE TITLE
Problem using URL as input: "Could not to read"

### ISSUE THREAD

**Issue by stefan-schweiger** [Azure/autorest#2670]
I want to use autorest to read my swagger json file from an URL as described in [this tutorial](http://michaco.net/blog/TipsForUsingSwaggerAndAutorestInAspNetCoreMvcServices).

But the command
```
autorest --input-file="http://localhost:51610/swagger/v1/swagger.json" --output-folder=Test --csharp
```

just returns the following error:
```
Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.1.0)
Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22)
FATAL: swagger-document-override/md-override-loader - FAILED
FATAL: Error: Could not to read 'http://localhost:51610/swagger/v1/swagger.json'.
FATAL: swagger-document/loader - FAILED
FATAL: Error: Could not to read 'http://localhost:51610/swagger/v1/swagger.json'.
Process() Cancelled due to exception : Could not to read 'http://localhost:51610/swagger/v1/swagger.json'.
Error: Could not to read 'http://localhost:51610/swagger/v1/swagger.json'.
    at ReadThroughDataSource.ReadStrict (C:\Users\<User>\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.azure\autorest-core\dist\lib\data-store\data-store.js:25: 19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169: 7)
```

When I access the file through my browser and save it locally I can use it as the input without a problem.

**Comment by fearthecowboy** [comment]
I wonder if it's the port number. I don't recall doing that, and I can't imagine why that would make a difference.

**Comment by stefan-schweiger** [comment]
After a bit of testing I've found out that when I start my project with Visual Studio (which uses IIS Express in font of Kestrel) to serve the swagger.json file I get the described error. When I start it via the "dotnet run" command it works just fine.

But it's still weird that both variants work fine in the browser but not via autorest.

**Comment by fearthecowboy** [comment]
Can you read it from something like powershell? `iwr http://localhost:51610/swagger/v1/swagger.json -outfile swagger.json` ?

Other cmdline apps?

**Comment by stefan-schweiger** [comment]
@fearthecowboy Ok after a bit more testing, it looks like the problem has to do with using Windows Authentication. I'm not sure how differently AutoRest and a browser handle requests, but for whatever reason Chrome and such forward this information and AutoRest does not.

I've tried to also enable Anonymous Authentication, but then I would need to work some magic to access the user from the HttpContext so this is not really viable for me.

`iwr` works if I add `-Credential <domain>\<user>`. But I do not realistically expect that AutoRest will add a feature to handle credentials because it's such an edge case. So I guess I will have resort to download my swagger.json file manually...

**Comment by kgreed** [comment]
I am having grief with this too. Having to save swagger.json as a file as a work around.
https://stackoverflow.com/questions/53508432/error-could-not-read-swagger-json-from-localhost-with-autorest

**Comment by calvaradocl** [comment]
I have changed my computer to a new one and having the same issue, same environment, I don't think that downloading the file locally is a solution at all (just a diy fix).

What is the real cause of this issue?

**Comment by fearthecowboy** [comment]
Are you attempting to use `https` with `localhost` ? If you haven't put a certificate on there, you shouldn't be using `https`,

**Comment by calvaradocl** [comment]
Hi, @fearthecowboy, yes I'm attempting to use https with an ASP Core 2.2 API, but the certificate was generated and it's on the computer.

![image](https://user-images.githubusercontent.com/17859695/55028735-42e73880-4fe7-11e9-9cf2-9e2ac61f62c7.png)

And the error that I'm receiving is the same as @stefan-schweiger 

PS C:\WINDOWS\system32> autorest --input-file='https://localhost:4002/swagger/AlertsSaaS/swagger.json' --csharp --output-folder=AlertsService.API.Client --namespace=AlertsService.API.Client  --override-client-name=AlertsServiceClient --verbose
>>
AutoRest code generation utility [version: 2.0.4283; node: v10.15.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\Carlos\.autorest\@microsoft.azure_autorest-core@2.0.4302\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4302)
No configuration found at 'file:///C:/WINDOWS/system32/'.
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: swagger-document-override/md-override-loader - FAILED
FATAL: Error: Could not read 'https://localhost:4002/swagger/AlertsSaaS/swagger.json'.
FATAL: swagger-document/loader - FAILED
FATAL: Error: Could not read 'https://localhost:4002/swagger/AlertsSaaS/swagger.json'.
Process() cancelled due to exception : Could not read 'https://localhost:4002/swagger/AlertsSaaS/swagger.json'.
  Error: Could not read 'https://localhost:4002/swagger/AlertsSaaS/swagger.json'.

**Comment by fearthecowboy** [comment]
Since it's nodejs, it's probably not able to verify the certificate.
