### ISSUE TITLE
Feature Request: Add option to suppress synchronous method generation

### ISSUE THREAD

**Issue by npnelson** [Azure/autorest#268]
Would it be possible to add a generation option that suppresses synchronous method generation (or maybe better, specify async, sync or both)?  

I only use async methods and the synchronous methods add clutter and open the door for future programmers on my project to fall into the trap of not using async for everything.

I can't think of a good name but maybe something like this 

-Synchronicity AsyncOnly|SyncOnly|Both

P.S. Recently discovered autorest and it looks like it could be a huge help for me

**Comment by markcowl** [comment]
@npnelson Thanks for the report - note that since this is a generator, you can always change the generated product before shipping your library.  Also, since this is an open source project, you could easily add this to your own generator based on ours.  We don't currently think this is required by enough customers to add an option.
