### ISSUE TITLE
x-ms-enum: Extensions support?

### ISSUE THREAD

**Issue by mdorda** [Azure/autorest#2701]
I am about to create PR which adds support for extending `x-ms-enum`, but I am not sure if it is something you want in master branch.

### What is the problem?
Extensions (`x-*` OpenAPI attributes) works like a charm for all models, but not for `x-ms-enum`. There is only support for **name**, **modelAsString** and **values**. But for a good reason, we need behaviour discribed below.

**OpenAPI**
```
...
"state": {
  "description": "Partner state",
  "enum": [
    "Active",
    "Inactive",
    "Deleted"
  ],
  "type": "string",
  "x-ms-enum": {
    "name": "PartnerState",
    "modelAsString": false
  },
  "x-company-namespace": "My.Custom.System.Shared.Namespace"
},
...
```
and I want to generate this like `AutoRest.Core.Model.EnumType` with following attributes:
- `ClassName, DeclarationName, WhateverName...` - PartnerState
- `ModelAsStringType` - false
- `Values` - ["Active", "Inactive", "Deleted"]
- **`Extensions` - [{"x-company-namespace": "My.Custom.System.Shared.Namespace"}]**
- ...

### Solution
We already have changed `ObjectBuilder.cs` in `autorest.modeler` project to support all `x-*` attributes for `x-ms-enum`. Shall I create a PR? Do you think it is usefull? Do you want to merge this behaviour to master?

**Comment by fearthecowboy** [comment]
We're trying to get away from introducing more _code-generation_ extensions in the OAI specs; ideally the spec should represent the wire format, and not tell clients how to generate their code. That information really belongs in the configuration.

You want to change the namespace for a generated enum class?  I think we can actually do that without a change to the modeler. This can probably be done via configuration with a transform `directive` now.

Lemme see if I can whip up a sample for you.

**Comment by fearthecowboy** [comment]
Oh; went an looked at your fork; we've split AutoRest into a bunch of smaller repositories this fall, so that we can ship different pieces independently.

If you push your code to your fork, at least I could see what you did...

**Comment by Murmand** [comment]
Oh, please ignore my fork. I deleted it right now just for to be sure 😃 It was outdated repository, we have moved it to our private repository few months ago.
I know about changes you are doing with autorest, we use it almost every day.

I am so sorry, it seems I am not able to write what is my problem... I will try again.

## Common model type

**OpenAPI**

```json
...
"UserInfo": {
  "required": [
    "id",
    "emailAddress"
  ],
  "type": "object",
  "properties": {
    "id": {
      "format": "int32",
      "type": "integer"
    },
    "fullName": {
      "type": "string"
    },
    "emailAddress": {
      "type": "string"
    }
  },
  "x-company-namespace": "My.Custom.System.Shared.Namespace"
},
...
```
`autorest.modeler` pass this model to generator as `AutoRest.Core.Model.CompositeType` with following properties:
- `Properties` - id, fullName and emailAddress
- **`Extensions` - [{"x-company-namespace": "My.Custom.System.Shared.Namespace"}]**
- and others

## x-ms-enum

```json
...
"state": {
  "description": "Partner state",
  "enum": [
    "Active",
    "Inactive",
    "Deleted"
  ],
  "type": "string",
  "x-ms-enum": {
    "name": "PartnerState",
    "modelAsString": false
  },
  "x-company-namespace": "My.Custom.System.Shared.Namespace"
},
...
```
`autorest.modeler` pass this model to generator as `AutoRest.Core.Model.EnumType` **without Extensions property**.

And if you look at this part of code https://github.com/Azure/autorest.modeler/blob/master/src/ObjectBuilder.cs#L58-L159 you can see that all vendor extensions (`x-company-namespace` in my case) is ignored and is not added to final model.

## Why we need that?

We use autorest to generate C# backend-to-backend API clients. And we have some models in NuGet packages which are shared over all projects. It is required (for a good reason) to not copy classes from NuGet packages to generated API client files. Example:

```json
"PartnerInfoProxy": {
  "type": "object",
  "properties": {
    "id": {
      "format": "int32",
      "type": "integer"
    },
    "externalId": {
      "type": "string"
    },
    "type": {
      "enum": [
        "Employer",
        "Insuree"
      ],
      "type": "string",
      "x-ms-enum": {
        "name": "PartnerType",
        "modelAsString": false
      },
      "x-vzp-namespace": "My.Custom.System.Shared.Namespace"
    }
  }
}
```

must generate C# model as

```C#
public class PartnerInfoProxy
{
    public int id { get; set; }
    public string externalId { get; set; }
    public My.Custom.System.Shared.Namespace.PartnerType type { get; set; }
}
```

We have already finished our generators to do that and we have already changed `autorest.modeler` to pass vendor extensions into `x-ms-enum` types, we do not need any help. The question is: "Is it a bug that the `ObjectBuilder.cs` (https://github.com/Azure/autorest.modeler/blob/master/src/ObjectBuilder.cs#L58-L159) do not add vendor extensions into final  `AutoRest.Core.Model.EnumType`, or is it a feature for some reason?"

Please, try to be patient, I know what I am doing, but due to the language barrier, I can not make it clear. Sorry.

**Comment by Grepsy** [comment]
@mdorda We have the same requirement as you mentioned. Did you guys solve this in the end? If so, would you like to share how?
