### ISSUE TITLE
Send trace to Application Insights

### ISSUE THREAD

**Issue by abatishchev** [Azure/autorest#2719]
What would be the recommended approach to send the trace produced by a Swagger-generated client to AI?  All is in C#. Please recommend some samples or reading materials.

**Comment by olydis** [comment]
Tracing is part of the client runtime, @shahabhijeet do you know how to do the above?

**Comment by abatishchev** [comment]
Yes, it is. I tried to add an ETW collector and AI ETW listener to redirect but it didn't work. So looking for some pointers. Thanks.

**Comment by abatishchev** [comment]
hi @shahabhijeet, please take a look

**Comment by shahabhijeet** [comment]
@abatishchev have you tried enabling TracingInterceptor?
In order to enable tracing you will have to have your TracingInterceptor class derive from IServiceLcientTracingInterceptor.
There isn't anything enabled out of the box.
Once you have the custom interceptor, enabled tracing similar to below
ServiceCLientTracing.AddTracingInterceptor();
ServiceClientTracing.IsEnabled = true;

**Comment by abatishchev** [comment]
Yes, that's what I did. Created my own implementations which uses AI TelemetryClient and added it later. So wondering whether there is anything built-in and you say there is not.

**Comment by abatishchev** [comment]
Do you plan to have something out of the box? If not, can you please talk to your PM to create a backlog workitem to consider in future?
