### ISSUE TITLE
Overriding param description fails schema validation

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#2863]
For the following snippet.
```json
        "parameters": [
          {
            "$ref": "#/parameters/StorageServiceProperties",
            "description": "The overridden description."
          }
        ]
```
AutoRest fails with the following error message.
```
ERROR: Schema violation: Data does not match any schemas from 'oneOf'
    - file:///C:/Users/jhendrix/Desktop/file-storage.json:52:8 ($["x-ms-paths"]["/?restype=service&comp=properties"].put.parameters)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
```

**Comment by dsgouda** [comment]
Dug into this a bit and per the OpenApi specification [here](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L1594) I don't think we allow any additional properties alongside a json reference. 
This also fails when validating against the swagger editor at [swagger.io](https://swagger.io/swagger-editor/)
However, technically speaking the [swagger specifications](https://swagger.io/docs/specification/using-ref/) say that the additional properties are ignored rather than considered semantically incorrect
Allowing such additional properties does sound like a non-trivial change to the schema.

@olydis thoughts?

**Comment by olydis** [comment]
@dsgouda Yes, but we already support `description`s alongside `$ref`s in other places (properties), which makes perfect sense in practice (documentation of type vs documentation of property). This issue is just about extending that logic to parameters, I don't think that should be hard to change in the schema (replicate whatever we do for properties).
@jhendrixMSFT This issue only talks about the schema, but do you actually expect description overriding to work? Not sure whether that already works (I'd be surprised), i.e. this might be another work item.

**Comment by dsgouda** [comment]
@jhendrixMSFT per discussions with @olydis I believe we definitely need to know whether we'd like to override the descriptions provided in model definitions to be overridden by the descriptions added to model references.
@salameer any guidelines here?

**Comment by dsgouda** [comment]
Closing this, if this is still an issue please reopen
