### ISSUE TITLE
Reduce the size of AutoRest?

### ISSUE THREAD

**Issue by scott-lin** [Azure/autorest#2871]
My goal is to npm install autorest as part of my build, package it up alongside my code, deploy the package to an agent, and then on said agent, run my code which invokes autorest.

For C# generation, I'm installing these packages:
```
@microsoft.azure/autorest-core: ^2.0.4245     \\ ~49 MB
@microsoft.azure/autorest.csharp: ^2.2.57     \\ ~18 MB
@microsoft.azure/autorest.modeler: ^2.3.43    \\ ~1 MB
```

Due to certain limitations, the maximum package I can deploy to an agent is ~26 MB. I cannot workaround this limit unfortunately.

Naturally, my next option is to reduce the size of my package. I'm compressing it, however, it is still too large. AutoRest isn't the only dependency I have, and even then, if I start adding other AutoRest extensions beyond C#, the size will bloat quickly.

This is probably a loaded question, but is there a way to reduce the sheer size of AutoRest? I'm crossing my fingers there are areas where bloat can be trimmed.

**Comment by olydis** [comment]
Hmmm no I'm not aware of a good way to easily reduce that size - most size is hidden in our dependencies (like .NET runtime), I don't think we can easily reduce those. @fearthecowboy ideas?

**Comment by fearthecowboy** [comment]
At this point... not really. 

AutoRest core itself is that size, because the size of its dependencies is that big.

What's worse, is that the c# extension is large, but that's not counting the .NET runtime that it downloads and installs on the fly (usually in $HOME/.net ) which it self is 65mb. 

There ain't no power in the verse that's going to be able to shrink the .NET runtime... Unfortunately, I don't have much of an answer at this point.

**Comment by scott-lin** [comment]
Thanks for the explanation!
