### ISSUE TITLE
 auto rest nodejs generation from yaml fails with  'cancelled due to exception : spawn EACCES '

### ISSUE THREAD

**Issue by mgara** [Azure/autorest#2873]
Hello,
Tries for the first time the autorest app, I'm trying to generate a nodejs client from a yaml spec.
Yaml spec is available here (I wrote the spec myself so I can make my life easier) : 

`wget https://app.swaggerhub.com/apiproxy/schema/file/mgara/Twitch/1.0.0-oas3/swagger.yaml
`
I had to install the icu package on CentOS 7 : 
`yum install icu -y
`
then I run the command : 

`autorest --input-file=swagger.yaml --nodejs --output-folder=.      
`  
```
AutoRest code generation utility [version: 2.0.4245; node: v7.10.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/root/.autorest/@microsoft.azure_autorest-core@2.0.4245/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4245)
   Loading AutoRest extension '@microsoft.azure/autorest.nodejs' (~2.1.25->2.1.40)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44->2.3.44)
Process() cancelled due to exception : spawn EACCES
  Error: spawn EACCES


```
It looks like there is some child spawn ... that trying to execute some binary file ... or just file access rights problem

**Env** : CentOS 7
**Node**: 7.10
**User** : root (god mode)

**Comment by fearthecowboy** [comment]
What happens if you don't run as root?

**Comment by rihardsk** [comment]
The same happens when running as a non-root user. I get the same error when trying to generate a C# client on Bash for Windows. It dies right after the `Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43->2.3.43)` step.

**Comment by fearthecowboy** [comment]
This is really bizarre. 

In the last six months, I've gotten like, 3 reports of `EACCES` problems, but I have no idea what's actually causing the issue.  

Still, the bigger problem you'll have with is that file is that we don't have support for OpenAPI 3 yet. (Still, it should have told you *that* rather than die in a useless way).

I'm going to ask a few questions to see if I can find *something* that I can reproduce to figure out what the issue is. These questions may or may not have anything to do with the problem, but I have to find a way to reproduce it.

- were you running in a VM or bare metal OS? 
- what processor does your machine have?
- how much memory do you have?
- is swap turned on?  How much swap space?
- did you try it under node on windows (note: this *should* not make a difference; just curious)
- Can you put ubuntu 16.04 on WSL instead? 
- (on full linux) does `dmesg ` say *anything* that might lead to an answer?

**Comment by mgara** [comment]
**were you running in a VM or bare metal OS?**
VM on vmware workstation player 12 on Surface book  i5 6300 CPU 8GB
**what processor does your machine have?**
i5 6300 CPU
**how much memory do you have?**
2GB 
**is swap turned on? How much swap space?**
swap 1.5 GB (used 0 GB)
**did you try it under node on windows (note: this should not make a difference; just curious)**
No
**Can you put ubuntu 16.04 on WSL instead?**
I'll try it later tonight
(on full linux) does dmesg say anything that might lead to an answer?
Nothing

btw : **kernel 3.10.0-693.21.1.el7.x86_64**
