### ISSUE TITLE
Generic response type

### ISSUE THREAD

**Issue by bugproof** [Azure/autorest#2945]
I have spec generated with Swashbuckle.AspNetCore

My actions return generic types like `ApiResponse<Person>`:

In spec it looks like:

```
"responses": {
     "200": {
         "description": "Success",
         "schema": {
             "$ref": "#/definitions/ApiResponse[IEnumerable[ContractorDto]]"
          }
      }
}
```

Autorest generates classes for each type:

ApiResponsePerson

**Comment by fearthecowboy** [comment]
AutoRest doesn't support generating generic types. 

It's not likely that we could even add support to handle such a situation.

**Comment by lecoque** [comment]
@fearthecowboy why?

**Comment by fearthecowboy** [comment]
I'm not even sure I can express the massive complexity of what you're asking for here. 

There is a really good reason why there is no generator that does that. The incredible amount of effort it would take to construct an abstract model that could support the concept in multiple languages, would be nothing less than astronomical.  

I'd be happy to review a PR that introduces such support across the supported languages, I'd be eager to see how the challenges of such an undertaking could be resolved.

**Comment by lecoque** [comment]
@fearthecowboy I don't think it's that massive as you describe it. Because there are already hints if type is generic in names (containing `[` and `]` and if not there's nothing wrong with providing some extension metadata to aid the generator.

For languages that support generics it shouldn't be that complex and I guess it would depend on that specific generator implementation...
