### ISSUE TITLE
PSSwagger replacement with AutoRest

### ISSUE THREAD

**Issue by JonKohler** [Azure/autorest#2952]
On https://github.com/PowerShell/PSSwagger/issues/414 it was mentioned the AutoRest team was working on a replacement for PSSwagger, for AutoRest generating a PowerShell module/client.

Was wondering if someone here could speak to this?

We're in the middle of writing a module for our company, and this is one of those things where we're saying, "there has GOT to be a better way to do this". So here we are. :)

**Comment by fearthecowboy** [comment]
It's on the way!

I demoed the pre-beta build to the PowerShell team today, and it went extremely well. 

I'm headed out on vacation for a couple weeks, and after I get back, it won't be very long till I post a beta.

**Comment by JonKohler** [comment]
Awesome! Would you be up on sharing pre-beta privately? We’re happy to contribute / hammer on it while your on vacation. We’re chomping at the bit on our module right now, so this would be both perfect timing and mutually beneficial.

Happy to take to a private message if that’s more appropriate - I’m jon@nutanix.com

**Comment by rileymckenna** [comment]
Has their been an update to the Powershell aspect of AutoRest?

**Comment by rhysjtevans** [comment]
Hey @fearthecowboy, struggling to create modules so would be up for participating in a private pre-beta too!

**Comment by fearthecowboy** [comment]
It's coming as soon as I can, I promise!

**Comment by JoelWiesmann** [comment]
Hey @fearthecowboy, do you have any news on this :-)?

**Comment by grock90** [comment]
Any updates on this?  Very eager to have cmdlets generated for pester level tests.

**Comment by fearthecowboy** [comment]
I have a prototype of the PowerShell generator : see https://github.com/Azure/autorest.incubator/blob/master/release-notes.md#incubator-release-notes-9162018 

I'm doing some AutoRest core work right now, and should be back on that in a couple weeks.

**Comment by grock90** [comment]
Garret,

Thank you so much for your response, I really do appreciate it.   At this time I'm running into an error that I just can't seem to get around.  Initially when I load the swagger.json file I get the following error.   I appreciate any help you can provide that helps me to move the ball forward.

___________________ERROR ENCOUNTERED_____________________

autorest : TypeError: Cannot read property 'url' of undefined
At C:\Build\user-data-service\Start-PsSwagger.ps1:92 char:9
+         autorest --use=@microsoft.azure/autorest.incubator@preview -- ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (TypeError: Cann...l' of undefined
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

    at new OperationMethod (C:\Users\gbarnes\.autorest\@microsoft.azure_autores
t.incubator@1.0.132\node_modules\@microsoft.azure\autorest.incubator\src\csharp
\lowlevel-generator\operation\method.ts:102:48)
    at new ApiClass (C:\Users\gbarnes\.autorest\@microsoft.azure_autorest.incub
ator@1.0.132\node_modules\@microsoft.azure\autorest.incubator\src\csharp\lowlev
el-generator\operation\api-class.ts:30:31)
    at Project.init (C:\Users\gbarnes\.autorest\@microsoft.azure_autorest.incub
ator@1.0.132\node_modules\@microsoft.azure\autorest.incubator\src\csharp\lowlev
el-generator\project.ts:68:5)
FATAL: TypeError: Cannot read property 'url' of undefined
FATAL: llcsharp - FAILED
FATAL: Error: Plugin llcsharp reported failure.
(node:55484) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported
failure.
    at GetPlugin_External (C:\Users\gbarnes\.autorest\@microsoft.azure_autorest
-core@2.0.4289\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pi
peline.js:114:19)
(node:55484) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch().
(rejection id: 6)
(node:55484) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.
(node:55484) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported
failure.
    at GetPlugin_External (C:\Users\gbarnes\.autorest\@microsoft.azure_autorest
-core@2.0.4289\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pi
peline.js:114:19)
(node:55484) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch().
(rejection id: 7)
Process() cancelled due to exception : Plugin llcsharp reported failure.
  Error: Plugin llcsharp reported failure.


___________________END OF ERROR____________________________




So I tried to manually edit the swagger document, I tried both servers and just url and still get errors.  Followed the documentation I discovered here: https://swagger.io/specification/#serverObject

--------------------------
"servers":[
        {
            "url":"http://localhost:8192/",
            "description":"developer"

        }
    ],
----------------------------------
__________Error Encountered_________
autorest : ERROR: Schema violation: Additional properties not allowed: servers
At C:\Build\user-data-service\Start-PsSwagger.ps1:92 char:9
+         autorest --use=@microsoft.azure/autorest.incubator@preview -- ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Schema v...ot allowed: url
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

    - file:///C:/Build/user-data-service/PsCmdlets/1.0.6/swagger.json:1:0 ($)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error
occurred. Exiting.
_________END ERROR_________________________

Then I tried just URL
______________ERROR ENCOUNTERED___________

__________Error Encountered_________
autorest : ERROR: Schema violation: Additional properties not allowed: url
At C:\Build\user-data-service\Start-PsSwagger.ps1:92 char:9
+         autorest --use=@microsoft.azure/autorest.incubator@preview -- ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Schema v...ot allowed: url
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

    - file:///C:/Build/user-data-service/PsCmdlets/1.0.6/swagger.json:1:0 ($)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error
occurred. Exiting.
_________END ERROR_________________________

{
    "swagger": "2.0",
    "url":"http://localhost:8192/",
    "info": {
        "version": "v1",
        "title": "UserData.Service",
        "description": "System of record for user settings, preferences, contact information, and other non-health related information"
    },
    "paths": {
        "/ECV/Status": {
            "get": {
                "tags": ["Ecv"],
                "operationId": "ECVStatusGet",
                "consumes": [],
                "produces": [],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/ECV/Ping": {
            "get": {
                "tags": ["Ecv"],
                "operationId": "ECVPingGet",
                "consumes": [],
                "produces": [],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            },
            "post": {
                "tags": ["Ecv"],
                "operationId": "ECVPingPost",
                "consumes": [],
                "produces": [],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/ECV/Slow": {
            "get": {
                "tags": ["Ecv"],
                "operationId": "ECVSlowGet",
                "consumes": [],
                "produces": [],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            },
            "post": {
                "tags": ["Ecv"],
                "operationId": "ECVSlowPost",
                "consumes": [],
                "produces": [],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/ECV/Crash": {
            "get": {
                "tags": ["Ecv"],
                "operationId": "ECVCrashGet",
                "consumes": [],
                "produces": [],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/ECV/LogLevel": {
            "get": {
                "tags": ["Ecv"],
                "operationId": "ECVLogLevelGet",
                "consumes": [],
                "produces": [],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/ECV/LogLevel/{logLevel}": {
            "post": {
                "tags": ["Ecv"],
                "operationId": "ECVLogLevelByLogLevelPost",
                "consumes": [],
                "produces": [],
                "parameters": [{
                    "name": "logLevel",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/UserData/{memberID}/BirthDate": {
            "get": {
                "tags": ["UserData"],
                "summary": "Return the DOB of the member.",
                "operationId": "UserDataByMemberIDBirthDateGet",
                "consumes": [],
                "produces": [],
                "parameters": [{
                    "name": "memberID",
                    "in": "path",
                    "required": true,
                    "type": "string",
                    "format": "uuid"
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        }
    },
    "definitions": {}
}
________________________________

**Comment by fearthecowboy** [comment]
AutoRest currently only supports OAI 2  (swagger)  ... Even though it converts it to OAI3 internally right away.  (so, `Servers[]` won't work)

(we've got a big update coming soon that adds the initial OAI3 support, but its tied to another big component... stay tuned) 

I can't see off the top what's wrong... if the prototype isn't working you'll have to wait until the new year. I'm rushing to get the core work we're doing done so I can get back to the PS generator.

**Comment by grock90** [comment]
Thanks so much for getting back to me promptly.  I was able to confirm that we're using the following Swagger and Swashbuckle items:

"Swashbuckle.AspNetCore/2.3.0": {
        "type": "package",
        "dependencies": {
          "NETStandard.Library": "1.6.1",
          "Swashbuckle.AspNetCore.Swagger": "2.3.0",
          "Swashbuckle.AspNetCore.SwaggerGen": "2.3.0",
          "Swashbuckle.AspNetCore.SwaggerUI": "2.3.0"
        },

Please do keep me open on your progress, as I know my team was really excited about the opportunity to have PS-Cmdlets for all of our services without having to develop them manually.

Happy holidays and I'll look forward to interacting with you after the new year.

Cheers,

Gary Barnes
________________________________

**Comment by MiYanni** [comment]
The AutoRest PowerShell generator has been created: https://github.com/Azure/autorest.powershell/
Closing.
