### ISSUE TITLE
Error "Assignment: Value '$ref' may not be undefined." reported when processing datamigration's swagger

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest#3395]
Error "Assignment: Value '$ref' may not be undefined." reported when processing datamigration's swagger (C:\git\azure-rest-api-specs\specification\datamigration\resource-manager\readme.md) when using autorest v3. 

The $ref is defined in swagger. From the code, seems the code expecting the value defined in Value.value instead of value.

![image](https://user-images.githubusercontent.com/6038235/73652888-e2bf2980-46c2-11ea-8dc8-3b353888deb6.png)

![image](https://user-images.githubusercontent.com/6038235/73654094-c96bac80-46c5-11ea-9e84-063593c56dea.png)

**Comment by RodgeFu** [comment]
@fearthecowboy  we are going to try our codegen on the DataMigration service soon. It will be helpful if you can help to have a look at the issue. thanks.

**Comment by fearthecowboy** [comment]
This is not valid:

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datamigration/resource-manager/Microsoft.DataMigration/preview/2018-07-15-preview/definitions/MigrateSqlServerSqlDbTask.json#L352-L371

You can not have a `$ref` in a definition and then other properties beside the `$ref` -- we bend the rules slightly to allow `description` (sometimes you want to describe the use of a $ref'd model differently than it's original description, ie, if you have a model called color, and you use it in for a property in `Car` for `BodyColor` and for `SeatColor` you'd want the property to have it's own description other than 'a color' ) 

But I have no idea what these models are trying to represent, it's not remotely legal swagger.  It doesn't get tripped up by the schema validator because JSON Schema doesn't have the fidelity to describe that.

It probably has been there so long because nobody ever tested the code that was generated from that.  I don't even know what it would have generated in V2. Probably just ignored the `allOf`, `x-ms-discriminator`, `type` when it saw `$ref` .

``` js
"MigrateSqlServerSqlDbTaskOutputValidationResult": {
      "x-ms-discriminator-value": "MigrationValidationOutput",
      "type": "object",
      "description": "Validation result for Sql Server to Azure Sql DB migration.",
      "$ref": "./MigrationValidation.json#/definitions/MigrationValidationResult",  // not legal with allOf, type, x-ms-discriminator-value 
      "allOf": [
        {
          "$ref": "#/definitions/MigrateSqlServerSqlDbTaskOutput"
        }
      ]
    },
    "MigrateSqlServerSqlDbTaskOutputDatabaseLevelValidationResult": {
      "x-ms-discriminator-value": "MigrationDatabaseLevelValidationOutput",
      "type": "object",
      "description": "Database validation result for Sql Server to Azure Sql DB migration.",
      "$ref": "./MigrationValidation.json#/definitions/MigrationValidationDatabaseLevelResult",
      "allOf": [
        {
          "$ref": "#/definitions/MigrateSqlServerSqlDbTaskOutput"
        }
      ]
    }
```

**Comment by RodgeFu** [comment]
Thanks for the details! we will check with service team on that.
