### ISSUE TITLE
Autorest should check Node version on start, and exit with a useful error message if version isn't supported

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/autorest#3460]
This will save users a lot of trouble if they install the latest Node version.  I did this earlier this week.

**Comment by fearthecowboy** [comment]
I'm not sure what you've seen:

```
C:\tmp\xx> nvs use 8
PATH -= $env:LOCALAPPDATA\nvs\node\13.11.0\x64
PATH += $env:LOCALAPPDATA\nvs\node\8.17.0\x64
C:\tmp\xx> npm  install -g autorest

> autorest@3.0.6187 preinstall C:\Users\garretts\AppData\Local\nvs\node\8.17.0\x64\node_modules\autorest
> node ./.scripts/preinstall-check




*******************************************************************************
  The version of Node.js 8.17.0 is not sufficent.
  You need to install Node.js v10.13.0 or greater.

  The prefered version is the current LTS (Long Term Support) version.
  see: https://nodejs.org/en/download/
*******************************************************************************

```

What did you see?

**Comment by seanmcc-msft** [comment]
The issue is that Node.js v11+ actually isn't compatible with AutoRest.  I tried using AutoRest with Node v12, and it started re-ordering the parameters of generated methods, and generating C# code that won't compile.

**Comment by fearthecowboy** [comment]
It's not really that easy to determine which releases of a given major node version don't work. Early Node 11 builds (<11.9?) were problematic, since they broke a few things internally, and then rounded back and fixed them up.

The only re-ordering that should ever happen is when there are optional parameters that precede required parameters. That hasn't changed.

**Comment by seanmcc-msft** [comment]
https://github.com/Azure/autorest/blob/master/docs/installing-autorest.md

"Install Node.js (10.15.x LTS preferred. May not function with Node < 10.x Be Wary of 11.x builds as they may introduce instability or breaking changes. )"

Why not just throw if the user isn't on Node v10?  We know it works with that version.

**Comment by fearthecowboy** [comment]
I used to. Node 12/13 introduced some really fantastic perf benefits that I couldn't ignore. 

I guess I could just blacklist node 11.x, and have it yell about that.

**Comment by seanmcc-msft** [comment]
@tg-msft.

AutoRest doesn't function correctly for me with Node v12.16.1.

**Comment by fearthecowboy** [comment]
Did you want to give a bit more detail? I have several people using node12.

**Comment by seanmcc-msft** [comment]
Try generating from [this swagger file](https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-12-12/blob.json) in .NET, with Node 12.16.1.

**Comment by tg-msft** [comment]
The (temporary) plugin we use for .NET's Storage Track 2 changes behavior between v10 LTS and v12 LTS around property enumeration order.  I'd prefer to just ignore the issue for now and wait until the new .NET Track 2 generator plugin is ready because it won't have that problem.

@seanmcc-msft - You can add a `node -v` version check to `azure-sdk-for-net/sdk/storage/generate.ps1` in the interim if you want to prevent anyone else on your team from running into this problem.
