### ISSUE TITLE
Please add support for generating Rust client

### ISSUE THREAD

**Issue by imp** [Azure/autorest#3502]
While AWS enjoys pretty extensive Rust support via `rusoto` framework, there is nothing for Azure. Having Rust client libraries automatically generated will accelerate adoption of the Azure cloud for Rust native application.

**Comment by ctaggart** [comment]
I would really like to see a AutoRest extension for Rust added as well. In fact, I would love to work on it at work if the opportunity came about. Meanwhile, I looked into what it would take to get this started and lay out what I think would work best for the architecture. I think it would be best to build the extension in Rust and target [WASI](https://github.com/WebAssembly/WASI). Rust has great code generation libraries like [syn](https://github.com/dtolnay/syn) and [quote](https://github.com/dtolnay/quote). That can be used to generate the code. rustfmt can be used as a library to format the generated code. All of those libraries compile to WebAssembly. That is [how ts2rust works](https://medium.com/@taggartsoftware/node-js-apps-with-rust-webassembly-27b6dd038c15), which I wrote. I am willing to contirbute some code from ts2rust under an MIT to help out this effort.

AutoRest extensions get launched as sub processses that then communicate using [JSON-RPC 2.0](https://www.jsonrpc.org/specification) with the main processs over stdio (stdin, stdout, stderr). This is where I got stuck and need help. What is the easiest way to get JSON-RPC 2.0 + Rust async + WASI? There are several available codebases that could be brought up-to-date, derviced from, etc. I'm not sure the easiest path. I would prefer Rust async that build off of [tokio](https://tokio.rs/). A target, probably the first one, for the generated code would be support for [reqwest](https://github.com/seanmonstar/reqwest) because we've been using it in production for a year and it support WebAssembly.

Here are some links to varios JSON-RPC 2.0 codebases:

- https://github.com/paritytech/jsonrpc/tree/master/stdio
  still on [futures 0.1](https://github.com/paritytech/jsonrpc/issues/485)
- https://github.com/rust-analyzer/lsp-server
- https://github.com/paritytech/jsonrpsee/ 
  [issues compiling as](https://github.com/paritytech/jsonrpsee/issues/122) cargo build --target=wasm32-wasi
- https://github.com/vorner/tokio-jsonrpc last updated 2018-05

**Comment by douyoung** [comment]
There was a similar request but covering more languages: https://github.com/Azure/autorest/issues/2452. I would love to see a Rust client generator too but I don't think the autorest team plans to support more languages in this project. Even the PHP support was dropped earlier due to the [reorg](https://github.com/Azure/autorest/issues/3064#issuecomment-557661090).

**Comment by nicw19** [comment]
You may want to try [OpenAPI Generator](https://openapi-generator.tech/) for the time being as it comes with both Rust client and server generators. The output needs some minor tweaks though for my use cases.

**Comment by daviwil** [comment]
It's not likely that our team will have resources to develop this officially so we will have to depend on the community to drive this effort.  @ctaggart's [AutoRust](https://github.com/ctaggart/autorust) is one example of such a project (thanks for spearheading that!)  I'm going to close this issue for now since it's not a request our team can fulfill for the forseeable future.
