### ISSUE TITLE
Not specifying license header in the config results incorrectly filled header

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest#3507]
Not specifying license header results in this header to be generated:

\# --------------------------------------------------------------------------
\# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6257, generator: {generator})
\# Changes may cause incorrect behavior and will be lost if the code is regenerated.
\# --------------------------------------------------------------------------

**Comment by daviwil** [comment]
Notes for my future self because I happened to find this while looking for something else:

- Definition of the default header string: https://github.com/Azure/autorest/blame/master/core/resources/default-configuration.md#L58
- Location in the code where `{generator}` should be getting filled in: https://github.com/azure/autorest/blob/master/core/lib/configuration.ts#L571

What is not obvious right now is how to get the name/version of the generator package.  I'll look into that the next time I come around to this.
