### ISSUE TITLE
Use the jsonpath-plus package for JSONPath evaluation

### ISSUE THREAD

**Issue by ohadschn** [Azure/autorest#3580]
The current jsonpath implementation is the following:
https://www.npmjs.com/package/jsonpath

There is a more advanced package which supports crucial features such as `@path`/`@parent`/`@property`/`@parentProperty`/`@root` shorthand selectors within filters: https://www.npmjs.com/package/jsonpath-plus

Please consider upgrading to it, we want to be able to do stuff like this:
```json
directive:
- from: swagger-document
  where: "$..responses[?(@property > 299 || @property < 200)]" // <= this requires jsonpath-plus
  transform: >
    $["x-ms-error-response"] = true;
```

**Comment by timotheeguerin** [comment]
I have looked into this (as the closed PR shows) and `jsonpath-plus` has some difference which I think is going to make this very hard to migrate to without breaking most people.

The main one being that it doesn't support double quotes `"` and only support `'` which to be fair is what the jsonpath spec define but this would be quite a breaking change for anyone using directives.

The other inconvenience is the the serialization of a jsonpath. `jsonpath-plus` does not try to simplify and serialize with quotes and brackets all the time making it harder to read.

**Comment by ohadschn** [comment]
Perhaps something to consider for the next major version then?

**Comment by timotheeguerin** [comment]
`jsonpath` library dependencies having a lot of vulnerabilities brought this back on the table. In the meantime jsonpath-plus also added support for `"` instead of `'` which solve the main breaking change this would have introduced. 
Believe we should now be able to use that library. 

It does seem however there hasn't been any updates in a while for `jsonpath-plus` either. We might have to make a fork later.
