### ISSUE TITLE
@autorest/core didn't pick the pinned version "3.0.6326", instead it picked the latest version

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest#3746]
We pinned `version: 3.0.6326` in `autorest.csharp` repo [here](https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#L1019
) but autorest picked `'@autorest/core' - '3.0.6348'` version instead.

For reference  check [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=657655&view=logs&j=b5cdfb1e-c180-561f-918e-a169e451719e&t=aff748e3-476c-56d1-ae31-4029fde28653&l=52).

**Comment by ShivangiReja** [comment]
Ahh, accidentally created this issue here.

**Comment by timotheeguerin** [comment]
So i have been looking at this and I think the main problem is that the config file only gets read by autorest-core hence it can't be used to pick the core version. This might not be that easy of a job. Maybe i am missing something if @daviwil you are saying Garrett used to have this working

**Comment by timotheeguerin** [comment]
So nvm my previous message, after looking more into this mess, there is some code to load a version of core to be able to load the config and try to extract the version. That code is crashing right now due to package not found, I believe this is due to the static-linked dependencies as that code is not started with static-linked

**Comment by timotheeguerin** [comment]
Lot of weird thing is happening here. I think there is 2 issues for the Charp readme in particular:
- When looking for config files autorest will look for files having this "Magic" string `\n> see https://aka.ms/autorest` to figure out if its a config file. Seems like the readme in the csharp is missing that so it just skip that file when trying to get the version.
- Something I fixed in the pr, though I am confused on how it ever worked then. Could you still try by just adding `> see https://aka.ms/autorest` to the readme and see if it works. If it does could you tell me what OS you are running this on?

**Comment by pakrym** [comment]
> Something I fixed in the pr, though I am confused on how it ever worked then. Could you still try by just adding > see https://aka.ms/autorest to the readme and see if it works. If it does could you tell me what OS you are running this on?

The configuration from the file is definitely loaded because it's now working fine and loading the version that's defined in the file again.

>see if it works

It does right now, what I wonder is how did we get broken by core change that we should've never loaded.

Does autorest try to load latest core first and then falling back to the one defined in the config?

> If it does could you tell me what OS you are running this on?

We have runs on windows and Linux, both failed.

Looking at the stack:

```
Error: Package '@autorest/core' - '3.0.6348' failed to install:
  Failed to install package 'https://registry.npmjs.org/@autorest/core/-/core-3.0.6348.tgz' -- Error: Process Failed.Error: Failed to install package '
    at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
    at async Object.selectVersion (D:\a\1\s\autorest.csharp\node_modules\autorest\dist\autorest-as-a-service.js:279:31)
    at async main (D:\a\1\s\autorest.csharp\node_modules\autorest\dist\app.js:275:31)
    at ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:590:23)
    at async Object.selectVersion (D:\a\1\s\autorest.csharp\node_modules\autorest\dist\autorest-as-a-service.js:279:31)
    at async main (D:\a\1\s\autorest.csharp\node_modules\autorest\dist\app.js:275:31)
```

It seems only `autorest` and `@azure-tools` are involved in loading. But we are using `npm ci` with a lock file so I expect to always get the same version of those.

**Comment by timotheeguerin** [comment]
Hhm yeah so the way it works(which kinda sucks) is it will try to download/use a version of core that is available to parse the config file. I guess this might have been your issue all along, that version had a bug that prevented from being downloaded. I really don't like this requirement to download core to execute that internal code, it is extremely prone to breaking, we can see if we can extract this to have autorest cli parse the file directly.

For the bug fix, I am then a little confused, wondering if this issue is only occurring when not passing the Readme explicitly

**Comment by pakrym** [comment]
Yeah, we did all the work to be in control of all the versions and avoid accidental breakage and it still got us.

**Comment by pakrym** [comment]
One option would be embedding a version of core into autorest itself instead of downloading latest. Or pinning the version of core that's downloaded to the version of autorest.

**Comment by timotheeguerin** [comment]
yeah the easiest solution would be to include core into the cli, just for that. Though the best might be to just extract the config  parsing section into a separate package that both the cli and core can consume

**Comment by daviwil** [comment]
A fix for this is issue has been published with the latest `autorest`:

```
npm install -g autorest
```

Let us know if this works for you!
