### ISSUE TITLE
LRO using Location header handle failed status

### ISSUE THREAD

**Issue by pavelprystinka** [Azure/autorest#3765]
Hi

I have an LRO described as:

    "/administration/phonenumbers/searches": {
      "post": {
        "tags": [
          "Search"
        ],
        "summary": "Creates a phone number search",
        "operationId": "PhoneNumberAdministration_CreateSearch",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "in": "body",
            "name": "body",
            "description": "Defines the search options",
            "schema": {
              "$ref": "#/definitions/CreateSearchOptions"
            }
          }
        ],
        "responses": {
          "202": {
            "description": "Accepted polling request",
            "headers": {
              "Location": {
                "type": "string",
                "description": "Url to retrieve the final update resource. Is a relative link"
              }
            }
          },
          "201": {
            "description": "Initial response with ProvisioningState='Succeeded'",
            "schema": {
              "$ref": "#/definitions/PhoneNumberSearch"
            }
          },
	 "default": {
            "description": "Failure",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "x-ms-examples": {
          "Create search": {
            "$ref": "./examples/CreateSearchAsync.json"
          }
        },
	"x-ms-long-running-operation": true,
        "x-ms-long-running-operation-options": {
          "final-state-via": "location"
        }		
      },
      ...
    },

Generated Operation is using ArmOperationHelpers to pull update from the server.
In the ArmOperationHelpers.UpdateStatusAsync method there is a call to check if terminal state is reached:
_hasCompleted = IsTerminalState(out string state);

ArmOperationHelpers.IsTerminalState is checking which header is used and then in case of Location uses Http status code to decide if terminal state is reached leaving `state` variable not assigned a value

if (_headerFrom == HeaderFrom.Location)
{
    return response.Status != 202;
} 

Back at ArmOperationHelpers.UpdateStatusAsync status check for failed status is missed and then Http status is checked again to decide whether to reserialize successful result or throw an exception for failure.

What status code server should return in case of operation failed? How to notify client side of the reason operation is failed? 

Thanks!

**Comment by iscai-msft** [comment]
adding @pakrym and @ShivangiReja since this is .net code. For Python, we use `202` in location polling to determine whether the polling is still in progress. However, we have a separate call before this to verify that the response code is in `[200, 201, 202, 204]`. How does .net do things

**Comment by lmazuel** [comment]
Hi @pavelprystinka 

I assume your question is about: what about a failure during the Location polling? Otherwise as @iscai-msft was saying, for the initial call the question is simple. There is no simple answer, as this is not defined in the ARM spec:
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#202-accepted-and-location-headers

The Azure-AsyncOperation or Operation-Location flow is more specific about status error:
https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#132-stepwise-long-running-operations
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#operation-resource-format

I'm closing this issue since this is not related to autorest, but it's a server question. I would suggest to have those conversation on our Teams channel instead.

Thanks!

CC @johanste
