### ISSUE TITLE
Is there a documentation about pre-namer

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#3896]
I run the modeler4 through cmd: 
```
npx autorest  https://github.com/Azure/azure-rest-api-specs/blob/a4bf7ce6447e7caf21edcb5a8c4c20e036b7a2a2/specification/machinelearningservices/resource-manager/readme.md --tag=package-2020-09-01-preview --v3 --output-artifact:code-model-v4 --use:@autorest/modelerfour@4.16.2
```
the output show the error:

```
FATAL: Error: Couldn't style name 'LabelingJobInstructions'. All of the following naming possibilities created duplicate names: [LabelingJobInstructions,LabelingJobInstructions]. You can try using 'modelerfour.lenient-model-deduplication' to allow such duplicates.
  Error: Plugin pre-namer reported failure.
```
If I run the above command with option: '--message-format=json' , the error detail even disappeared
```
{
  "sources": []
}
  Error: Plugin pre-namer reported failure.
```

If there is a document tell about how it woks , it will be useful for fixing the issue. Otherwise I need to try to guess what may causes this issue

**Comment by timotheeguerin** [comment]
Believe the issue here is that you have an anonymous schema https://github.com/Azure/azure-rest-api-specs/blob/a4bf7ce6447e7caf21edcb5a8c4c20e036b7a2a2/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2020-09-01-preview/mfe.json#L5710

which defaults its name to be `LabelingJobJobInstructions` but then autorest tries to remove the duplicate consequtive words `Jobs` which create `LabelingJbInstructions` which is a schema already defined. 
Now it should actually not be removing the duplicate if it finds a conflict. I guess this must be a order of definition which cause this

**Comment by timotheeguerin** [comment]
I believe there seems to be some issues when error are thrown they don't get logged according to the message format.

**Comment by jianyexi** [comment]
> I believe there seems to be some issues when error are thrown they don't get logged according to the message format.

Have you figured out the cause of the issue ?
