### ISSUE TITLE
New Duplicate Operation 'X' detected when bumping autorest

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#3921]
From our CI after bumping autorest:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=748819&view=logs&j=1a6ae1a5-56d5-51f8-8f8d-f67115b54b1a&t=937f187a-1519-5cb7-77a5-47832257e788

```
ERROR (): Duplicate Operation 'Register' detected.

ERROR (): Duplicate Operation 'List' detected.

ERROR (): Duplicate Operation 'Create' detected.

ERROR (): Duplicate Operation 'Update' detected.

ERROR (): Duplicate Operation 'Get' detected.

ERROR (): Duplicate Operation 'Delete' detected.

ERROR (): Duplicate Operation 'List' detected.

ERROR (): Duplicate Operation 'List' detected.
FATAL: Error: 8 errors occured -- cannot continue.
```

**Comment by timotheeguerin** [comment]
I think for this one it is due to some invalid configuration that result in multiple version of the same Api being loaded.

https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/softwareplan/resource-manager/readme.md

![image](https://user-images.githubusercontent.com/1031227/108924422-770e6e00-75ef-11eb-921a-8302927c0ec2.png)
You can see here it first define `tag: package-2019-06-01-preview` which enable the condition to load the `preview` version spec
but then it override that tag with `package-2019-12-01` which then adds the non preview spec file. So you end up with both versions.

I think one of the 2 `tag:` assignement needs to be  removed.
