### ISSUE TITLE
autorest M4 duplicate schema error

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#3939]
**Describe the bug**
```
Please provide as much information as you can. This would be: 
- OpenAPI files having the issues
- Autorest command used
autorest  --input-file=https://github.com/Azure/azure-rest-api-specs/blob/9655fc4ac6c3cead5ee38ba376bee8f4d47182d3/specification/providerhub/resource-manager/Microsoft.ProviderHub/stable/2020-11-20/providerhub.json  --v3 --output-artifact:code-model-v4 --use:@autorest/modelerfour@4.16.2 --debug 
```

**Expected behavior**
The output contains an exception:
- FAILURE  {} Error: Couldn't style name 'CustomRolloutProperties'. All of the following naming possibilities created duplicate names: [CustomRolloutProperties,CustomRolloutProperties]. You can try using 'modelerfour.lenient-model-deduplication' to allow such duplicates.
-

**Additional context**

**Comment by timotheeguerin** [comment]
Hi @jianyexi 

problem here is you those anoymous object which name can't be resolved because the guessed name is already taken.

Here `CustomRollout` has a property called `properties` which type doesn't have a name so it tries to name it `CustomRolloutProperties` but there is already a definition called `CustomRollout`
```
"CustomRollout": {
      "description": "Rollout details.",
      "type": "object",
      "required": [
        "properties"
      ],
      "allOf": [
        {
          "$ref": "../../../../../common-types/resource-management/v2/types.json#/definitions/ProxyResource"
        }
      ],
      "properties": {
        "properties": {
          "allOf": [
            {
              "$ref": "#/definitions/CustomRolloutProperties"
            }
          ],
          "description": "Properties of the rollout."
        }
      },
      "x-ms-azure-resource": true
    },
```

You can either use `modelerfour.lenient-model-deduplication` as suggested in the error or extract this type and give it an unique name.

Also changing to that just works(Remove the intermediate type)
```json
 "properties": {
        "properties": {
          "$ref": "#/definitions/CustomRolloutProperties"
        }
      },
```
