### ISSUE TITLE
autorest/C# Add new optional parameters to the end of method signatures

### ISSUE THREAD

**Issue by Sandido** [Azure/autorest#3957]
**Describe the bug**

This is more of a feature request. 
We made edits to the Swagger file in the Rest API repository. One of the edits was adding a [new optional property](https://github.com/Azure/azure-rest-api-specs/blob/0cb29c3a2ff50ba9c9c0210fa693a627d770135a/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L7408) called platformFaultDomain. 

We generated the .Net/C# SDK from this swagger using the autorest cmd seen here:
```
cmd.exe /c autorest.cmd "<your_local_swagger_folder>\specification\compute\resource-manager\readme.md" --csharp --version=2.0.4413 --reflect-api-versions --csharp-sdks-folder="<your_local_sdk_folder>"
```

The new optional parameter was added to the [middle of the relevant method signatures](https://github.com/Azure/azure-sdk-for-net/pull/18498/files#diff-5b94694049851a26075ef7c1360f85076549a418c9aefd5bf895e6c826a40839L147). 
However, adding the optional parameter to the middle of the signature is a breaking change for .Net and requires a Customization to overload the method. 

Can you change autorest to add optional parameters to the end of the parameter list for .Net generation? 
I think this would be fine in other SDKs too. 

**Expected behavior**
Autorest should add new optional method parameters as the last parameter in the method signature for .Net SDK. I think this would be fine in other SDKs too. 

**Additional context**

**Comment by timotheeguerin** [comment]
Hi @Sandido is that the same feature request as #3662?

**Comment by Sandido** [comment]
@timotheeguerin , it is not quite the same issue. 
.Net SDK does need the optional parameters to be at the end of the method signature, but my ask is even more specific. That new optional parameters being added to the methods be added as the last parameter in the signature. 

Sorry, I thought my links would send you to the specific line in the PR that was relevant. 
[The new optional parameter platformFaultDomain ](https://github.com/Azure/azure-rest-api-specs/blob/0cb29c3a2ff50ba9c9c0210fa693a627d770135a/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L7408)= line 7408 of the compute.json file in that PR.

[middle of the relevant method signatures](https://github.com/Azure/azure-sdk-for-net/pull/18498#discussion_r574029803) = sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/VirtualMachineUpdate.cs line 142 in the linked PR.

**Comment by timotheeguerin** [comment]
I see, if I understand the issue is with newly added optional parameters, you'd want a way to be able to place those last.

**Comment by pakrym** [comment]
Autorest has no notion of "newness" of a particular API because it only sees the latest version of the swagger and doesn't make decisions based on diffs between them.

In this case, the `platformFaultDomain` is part of a flattened `properties` object. The flattened object's properties are inserted into a position of the `properties` and it's defined before `identity` or `zones`: https://github.com/Azure/azure-rest-api-specs/blob/0cb29c3a2ff50ba9c9c0210fa693a627d770135a/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L9943-L9957

That's why the new property ends up where it does in the order.

**Comment by Sandido** [comment]
@pakrym , @timotheeguerin , 
Do you see any way to implement this type of change? Perhaps a tag in Swagger to order the parameters?

**Comment by pakrym** [comment]
Not that I know of.

**Comment by Sandido** [comment]
@pakrym , can you consider taking this up for investigation?
Right now we are mitigating these breaking changes by adding Customizations: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations 

We need to overload the methods that are changing with a new optional parameter in the middle of the method signature with a new method for each optional parameter that is after the new one. This Customization folder will continue to grow over time with no end in sight.

**Comment by pakrym** [comment]
cc @chamons

**Comment by Sandido** [comment]
@timotheeguerin , @pakrym , @lmazuel , 
Will this be taken up for investigation at some point?

**Comment by timotheeguerin** [comment]
@Sandido I don't see this making sense to have something at the autorest level. Each language treat parameters differently and might add additional ones(in the case of csharp `customHeaders` and `CancellationToken` gets added at the end, in typescript optional parameters get grouped in an object automatically at the end). This would require a per language configuration, don't feel like this is maintainable. CSharp could potentially have a similar pattern as typescript for optional params @pakrym what do you think?

Have you looked into using `x-ms-parameter-grouping` https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-parameter-grouping it will create an object for parameters instead of positional params letting you add more optional value without any breaking changes.

**Comment by pakrym** [comment]
The change to the pattern we use for parameters would be a breaking change in itself. In addition, we are dialing down that V2 generator investment outside of the critical bug fixes.
