### ISSUE TITLE
Error: Collision detected inserting into object: constructor

### ISSUE THREAD

**Issue by SPEMoorthy** [Azure/autorest#3967]
We are not able to generate C# Client.

We tried with V2 format and also V3 (Open API Format) Both are giving same problem.

Note: Attached Screenshot. and Swagger Generated JSON.
![AutorestError](https://user-images.githubusercontent.com/4408733/110419795-0459c400-80c0-11eb-8e55-653e4e09ac42.png)
[Api.txt](https://github.com/Azure/autorest/files/6105909/Api.txt)
[ApiV2.txt](https://github.com/Azure/autorest/files/6105911/ApiV2.txt)

Regards,
@spemoorthy

**Comment by timotheeguerin** [comment]
Hi @SPEMoorthy how are you creating those swagger files? I believe the issue here is you have an attribute called `constructor` which is a reserved word in js. It seems like in your definitions/schemas you have all of the csharp metadata types(`CustomAttributeData`, `ConstructorInfo`, etc.) I believe those are added incorrectly and will create issue down the line(specially with chsarp)

**Comment by SPEMoorthy** [comment]
Hi @timotheeguerin,
Thanks for your findings. Swagger file is generated with the help of **Swashbuckle.AspNetCore.Swagger, Version=6.1.0.0**. I renamed attribute constructor to constructorInfo. Error vanished. 

Regards,
@SPEMoorthy
