### ISSUE TITLE
Writing transforms is very difficult, can we warn on common mistakes?

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#4054]
**Is your feature request related to a problem? Please describe.**
Writing autorest transforms is rather non-trivial for someone new to the space (like myself). 

It is pretty easy to write something that doesn't do what you expect. Could we possibly catch some obvious "you are doing it wrong in transforms" and emit warnings.

**Describe the solution you'd like**
I don't know the things I don't know yet, but the one that comes to mind is "your transform's where matched zero elements in the swagger".

Maybe there are a bunch of other mistakes that are easy to catch?

**Describe alternatives you've considered**
Doing nothing is always an option here. People figure it out over time.

https://jsonpath.com/ is apparently helpful in tracking down your where mistakes. 

**Additional context**

**Comment by timotheeguerin** [comment]
If there is an error in the transform code, I believe it should be logging that but otherwise I agree that figuring out what is wrong with directives is very hard right now. I have thought of a few things that could improve, specially around logging what path the selector found, what is the input, output, etc
