### ISSUE TITLE
missing required input should throw an error or fallback gracefully

### ISSUE THREAD

**Issue by archerzz** [Azure/autorest#4131]
**Describe the bug**

- Run `autorest --input-file=xxx.json`, and it will return `Generation Complete`.

```
AutoRest code generation utility [cli version: 3.2.0; node: v14.16.1, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\xxx\.autorest\@autorest_core@3.4.1\node_modules\@autorest\core\dist' (3.4.1)
[4.99 s] Generation Complete
```
- But actually it doesn't generate anything, you need to specify language.

**Expected behavior**

- Throw error if some inputs are required.
- Or fallback gracefully. For this case, we could return message like `No language specified. No code generated`.

**Additional context**

N/A

**Comment by timotheeguerin** [comment]
Similar to the flag problem, autorest is just a orchestrator and pipeline runner, it isn't limited to SDK generation even if it is its main purpose. Custom extension can be written and added to the pipeline. Providing `--python` or `--go` just loads the python or go extension for example. There isn't really a way autorest could know if generation was completed as expected due to missing flags(and so extensions)
