### ISSUE TITLE
How to define request Accept header with constant value so user of a client do not need to specify it as a parameter

### ISSUE THREAD

**Issue by boris-tarasov-maersk** [Azure/autorest#4142]
I would like to hear your suggestions on how to add Accept header to a request while generating a client from openapi v3.

My goal is to specify Accept header that is used to control content and version of API just as GitHub and other API vendors are doing so our URL are stable but returned content depends on Accept header value.
Example value of Accept header: "application/vnd.admiral.v2+json".

Client code is API specific. So in this case I am trying to generate client code that will work with only v2 and json. In this case Accept header value is constant. 

Your first immediate response might be to send me to 
https://swagger.io/docs/specification/describing-parameters/#header-parameters
with a notion that "Header parameters named Accept, Content-Type and Authorization are not allowed."
But documentation only specifies on how to define Accept header for response, it does not explain on how to define Accept header in a request.

I tried to add Accept header in the following way:

```
paths:
  '/products/{productCode}/teams':
    parameters:
      - $ref: '#/components/parameters/productCode'
    post:
      summary: Create Product Team
      description: Adds a new Team to a Product
      operationId: AddTeam
      parameters:
        - $ref: '#/components/parameters/apiVersionAcceptHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequest'
      tags:
        - Admiral Teams
      responses:
        '202':
          description: Success - Team Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        default:
          $ref: '#/components/responses/ErrorResponse'
...
  parameters:
    apiVersionAcceptHeader:
      name: Accept
      in: header
      description: Set this header value to "application/vnd.admiral.v2+json" to indicate that expected value is json API v2
      schema:
        type: string
        default: application/vnd.admiral.v2+json
      required: false
```
I see that code somehow recognizes Accept header but I do not see it being added to header list in the request:

![image](https://user-images.githubusercontent.com/75432520/119025384-5d898200-b9a4-11eb-9a79-abcf5e93d6a8.png)

![image](https://user-images.githubusercontent.com/75432520/119026074-0fc14980-b9a5-11eb-97fe-497217b09ffa.png)

problem exists in both go and c# code.

**Comment by timotheeguerin** [comment]
Hi @boris-tarasov-maersk as you saw in the spec `Accept` is not allowed to be a header. Accept is only a request header and the documentation describe what a response can return as a content-type(and so what can be requested with the accept header) as expected.
You'll need to set the response content with the list of allowed content-type

```yaml
 content:
   application/vnd.admiral.v2+json:
     ...
```

**Comment by boris-tarasov-maersk** [comment]
> Accept is only a request header 

Yes, And I want to define a REQUEST header, not a response header

**Comment by timotheeguerin** [comment]
@boris-tarasov-maersk, to define an `Accept` header for a request you have to define the possible responses `Content-Type`. This is how OpenAPI 3 spec works. 

Now autorest doesn't support multiple response `Content-Type` and so multiple values for the `Accept` headers. 
So as much as you can have your request pass `Accept: application/vnd.admiral.v2+json` using 
```yaml
 content:
   application/vnd.admiral.v2+json:
     ...
```
instead of 
```yaml
 content:
   application/json:
     ...
```
autorest will unfortunately at this time not work if you try to add additional responses type. Only the first one will be saved.

Autorest right will allow the `Accept` header being added as a parameter as you did (even if this is NOT allowed in the OpenAPI specs), so for that it seems like the issue is in how the go and csharp library are generated but not autorest. I would open an issue on their corresponding repos https://github.com/Azure/autorest.csharp and  https://github.com/Azure/autorest.go.
Note that even if this is allowed right now, this might not remain as this is not up to spec. It also bring no value to be able to do that as you still can't configure the response schema depending on the `Accept` header.

**Comment by boris-tarasov-maersk** [comment]
still did not have time to review. Please do not close

**Comment by boris-tarasov-maersk** [comment]
@timotheeguerin 
thanks but to clarify:
  content is only available for some of HTTP vers like POST
  GET does not have content. 
Or you are talking about some other part of request?

**Comment by timotheeguerin** [comment]
Yes `Get` doesn't have a request body but it has a response body which content-type should be the same as the **request** `Accept` header.
You need to describe the potential **responses** and that will correspond to the **accept** header you can send in the **request**.

**Comment by boris-tarasov-maersk** [comment]
but content-type is used to describe what I am seding to the server. it could be json but it could also be a binary or any other type. Why mix those things?
What you say is that lets use header that should signal type of data sent to indicate what I want to get in response.
