### ISSUE TITLE
Not able to use v2 extension for C# code generator

### ISSUE THREAD

**Issue by arpit-gagneja** [Azure/autorest#4419]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

I am using the below autorest command but getting error that Failed to install or start extension '@microsoft.azure/autorest.csharp' (~2.3.79)

![image](https://user-images.githubusercontent.com/19483623/153336808-1bb6d0ff-3b76-4f7a-8eae-61254a6b1288.png)

**Expected behavior**
I need to use legacy code generation for C# as our existing code is checked using that.

**Additional context**

**Comment by necusjz** [comment]
@timotheeguerin , I got a same issue with `@autorest/az` extension:
![image](https://user-images.githubusercontent.com/12371639/155279447-e9b4df01-666c-4646-b1c2-66594c0a3917.png)

1. I have tried `autorest --reset` but this issue was still here.
2. Yes, I can separately install `@autorest/az` (but it will not be displayed in `~/.autorest`).
3. There is no `package.json` and `node_modules` under `~/`.

**Comment by timotheeguerin** [comment]
Hi @necusjz, I got a few more question for your case:
1. Are you behind a proxy? 
2. Can you rerun with the latest version of `@autorest/core` (--version flag should be `3.7.5`) and `--debug --verbose`. Since the version you are using here there has been a lot of improvements in the logging of errors when installing packages.

**Comment by necusjz** [comment]
@timotheeguerin , thanks for your information, the latest version works.
