### ISSUE TITLE
Cryptic Error Message when generating module

### ISSUE THREAD

**Issue by georgend** [Azure/autorest#4503]
When generating a module we are getting the error message

```
PLUGIN FAILURE: Cannot read property 'enum' of undefined, TypeError: Cannot read property 'enum' of undefined
```

Any clues or pointers regarding the cause of the error?

Full Log Attached [here](https://gist.github.com/georgend/e5f2f845f5693b9bf7f491475ac65e53)

**Comment by peombwa** [comment]
@georgend, the issue was with how the key segment parameter object was defined in the OpenAPI file as described in https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/902#issuecomment-1062443630. 

We can close this issue since this has already been fixed in the OpenAPI file. A complete support will be provided by https://github.com/Azure/autorest/issues/4480.
