### ISSUE TITLE
`underscore` is a devDependency instead of dependency

### ISSUE THREAD

**Issue by tjanczuk** [Azure/autorest#599]
The module fails to load for lack of `underscore` when installed for production. 

Repro:

```
npm i --production ms-rest-azure
node -e 'require("ms-rest-azure")'
```

This should load just fine, but instead results in 

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/tomek/projects/node_modules/ms-rest-azure/lib/azureEnvironment.js:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by amarzavery** [comment]
@tjanczuk - thanks for pointing this out. Will fix this in the upcoming release.

**Comment by amarzavery** [comment]
@tjanczuk - Hi Tomasz, New version of the client runtime `ms-rest-azure` has been published. I have tested it and this issue is resolved. 

I had attended your seminar on running .net and node.js in process @mixpo about a year ago. It is nice to know that you tried the auto generated library. It would be nice if you could review the autorest generated [storage mgmt. library](https://github.com/Azure/azure-sdk-for-node/tree/autorest/lib/services/storageManagement2) (to be published) and provide feedback.

Thanks,
Amar

**Comment by tjanczuk** [comment]
Thanks! I think a number of upstream azure-* libraries that depends on ms-rest-azure will need to be updated with that version as otherwise they also experience the same problem. 

I am not as much playing with these libraries myself as attempting to make them part of https://webtask.io platform. I believe @sandrinodimattia has plans to create some collateral around web tasks and azure later on.

**Comment by amarzavery** [comment]
This is the new code generator and service teams are onboarding. The libraries dependent on ms-rest-azure have ben updated. Closing this as the issue has been resolved.
