### ISSUE TITLE
Add more Documentation for Mac/Linux

### ISSUE THREAD

**Issue by schmitch** [Azure/autorest#632]
Currently I try to compile this project under Mac/Linux, however with the default commands I would do the following:

```
dnu build
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231

Unable to locate project.json.
Total build time elapsed: 00:00:00.0037569
Total projects built: 1
```

Since there is no project.json it would not work.

**Comment by stankovski** [comment]
I would recommend using gulp to build everything (https://github.com/Azure/autorest#gulp). 

Currently dnx support in AutoRest is limited. Since we plan to move to [dotnet/cli](https://github.com/dotnet/cli) in the near future to generate truly cross-platform experience I will close the issue. Once we migrate to dotnet/cli we will update the documentation
