### ISSUE TITLE
AutoRest to handle "x-ms-pageable" and ListNext() function?

### ISSUE THREAD

**Issue by huangpf** [Azure/autorest#731]
Is it feasible for AutoRest to handle "x-ms-pageable" internally and do not expose ListNext() function?

Pagination is a more of a REST API requirement, but it's less preferred on the client function side.

**Comment by matthchr** [comment]
+1 to this feature request, although there are a couple of things to consider:

1. The case where people want to "key into" a list with a `nextLink` which they gathered from some other place.
2. It requires a careful consideration of async/sync because in many languages you want to expose the API `ListFoo` as returning a collection or enumerable of `Foo`'s - but you want to allow synchronous and asynchronous enumeration.
3. You probably want Lazy evaluation because the server-side collections could be quite large.
4. Playing nice with the built in language looping mechanism (`foreach` and the like) is ideal.

It's worth taking a look at the generated Python code as I believe that it supports the above cases and still has the default list experience not dealing with pages/nextLink.

Or in C# an example might look something like:

`public IPagedEnumerable<Foo> ListFoo(...)`

where `IPagedEnumerable<Foo>` is a type which looks like so:
```
    public interface IPagedEnumerable<T> : IEnumerable<T>
    {
        IPagedEnumerator<T> GetPagedEnumerator();
    }
```

and `IPagedEnumerator<T>` looks like:

```
    public interface IPagedEnumerator<T> : IDisposable
    {
        T Current { get;}

        Task<bool> MoveNextAsync(CancellationToken cancellationToken = default(CancellationToken));

        Task ResetAsync(CancellationToken cancellationToken = default(CancellationToken));
    }
```

**Comment by fearthecowboy** [comment]
Howdy!

In our planning for driving towards a stable '1.0' release, I'm marking this issue as 'deferred' :zzz: and we're going to review it during the post-1.0 planning cycle. 

_It's not to say that we're not going to work on it, or that this isn't not important, but at the moment, we're picking and choosing the stuff we **must** do before 1.0._ :horse_racing:  :horse_racing:  :horse_racing: 

We'll make sure we pick this back up at that point. :tada:
