### ISSUE TITLE
Java: encapsulate the retrofit type into autorest type

### ISSUE THREAD

**Issue by xingwu1** [Azure/autorest#744]
In current async method, we always return retrofit type Call<Response>, however, end user may not have knowledge of internal retrofit implementation. So we should create AutoRestResponse class to encapsulate the retrofit Call object. Same idea apply to other retrofit type and okhttp type.

**Comment by jianghaolu** [comment]
As of pull request https://github.com/Azure/autorest/pull/737,
- Async methods all return type `ServiceCall` which has `cancel()` method. `AutoRestResponse` sounds like there is an actual response in there.
- `ServiceCall`'s cancel method is wired up with long running operation cancellation and paging cancellation.
- Method group interface doesn't expose network layer components.

What still needs to be done since client interface still exposes okhttp3.Interceptor and log level:
- Wrap interceptor (in fact, there is a complete interceptor re-work)
- Wrap logging and allow custom logging (slf4j pluggable, etc)
