### ISSUE TITLE
Error in `acquire_token': Couldn't login to Azure, please verify your tenant id, client id and client secret (MsRestAzure::AzureOperationError)

### ISSUE THREAD

**Issue by parth618** [Azure/autorest#767]
Even though i passed the tenant_id, client_id, client_secret for creating token. And generated the token as 
token_provider = MsRestAzure::ApplicationTokenProvider.new(tenant_id, client_id, client_secret)
credentials = MsRest::TokenCredentials.new(token_provider)

Unable to identify why the error is appearing as the subscription/Active directory state is active.
The error appears when i try to create ResourceGroup/storage profile/vm with azure_mgmt_compute using azure-ruby-sdk
![acure_credential_error](https://cloud.githubusercontent.com/assets/17052093/13419431/2ed3a196-dfa4-11e5-9728-4d44c118bf88.PNG)

**Comment by stankovski** [comment]
@devigned can you take a look?

**Comment by parth618** [comment]
Dose this error relates to type of application i.e. whether the application is Native Client App or Web App ??

**Comment by devigned** [comment]
Just about to drop in http logging (https://github.com/Azure/autorest/pull/788) to provide a view of the http traffic to help debug. Use `export AZURE_HTTP_LOGGING=full` (or 'partial' if you don't want bodies).

I expect this issue is due to either setting up a service principal incorrectly (which is very easy to do native / web) or not providing the service principal a contributor or owner role in the service.

**Comment by devigned** [comment]
@parth618 also, this article gives you the details on [how to create a service principal in Azure CLI] (https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/)

**Comment by parth618** [comment]
May be the issue was co-admin got deleted
Thanks

**Comment by devigned** [comment]
@parth618 my pleasure! We're here to help.
