### ISSUE TITLE
Path length problems when building Generator.Auzre.Python.Tests

### ISSUE THREAD

**Issue by brodyberg** [Azure/autorest#895]
I see this after: 
- `git fetch upstream`
- `git pull upstream/master`
- Visual Studio clean
- Visual Studio build

```
1>------ Build started: Project: AutoRest.Generator.Azure.Python.Tests, Configuration: Net45-Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3021: Unable to copy file "C:\Users\...\Documents\GitHub\autorest\AutoRest\Generators\Python\Azure.Python.Tests\Expected\AcceptanceTests\AzureParameterGrouping\autorestparametergroupingtestservice\models\parameter_grouping_post_multi_param_groups_second_param_group.py" to "bin\Net45-Debug\Expected\AcceptanceTests\AzureParameterGrouping\autorestparametergroupingtestservice\models\parameter_grouping_post_multi_param_groups_second_param_group.py". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4466,5): error MSB3541: Files has invalid value "bin\Net45-Debug\Expected\AcceptanceTests\AzureParameterGrouping\autorestparametergroupingtestservice\models\parameter_grouping_post_multi_param_groups_second_param_group.py". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
========== Build: 0 succeeded, 1 failed, 8 up-to-date, 0 skipped ==========

```

**Comment by brodyberg** [comment]
@annatisch Do you see this?

**Comment by annatisch** [comment]
Sorry @brodyberg , I hadn't :)
To be honest I can't run the autorest project in the default Windows GitHub path (\Users\Me\Documents), as the paths involved in the generated tests just become very long.
This is due to:
a) The test are often generated with very-wordy names that wouldn't normally be used for a client like:
parameter_grouping_post_multi_param_groups_second_param_group
b) We generate using python naming conventions (words separated with underscores) which makes it worse.

I was forced to pull the code in to a shorter path, like C:\Code\Github.

Having said that - I'm not sure why it's attempting to copy the generated tests into the .NET bin directory. Can I ask which solution/project you are building from?

Thanks!
Anna

**Comment by brodyberg** [comment]
@annatisch This makes sense (changing your path). I am just building autorest.sln.

**Comment by annatisch** [comment]
I'm not sure what to suggest - as the autorest.sln file has never built from scratch for me due to errors setting up some of the .NET dependencies....
I usually just build autorest.proj specifically, then run the test re-generation and test runs from the cmd line...

**Comment by annatisch** [comment]
@brodyberg  - were you able to get this to build in the end?

**Comment by brodyberg** [comment]
No, but if no one cares let's close.

**Comment by olydis** [comment]
If this is still a concern, reopen it with new details.
