### ISSUE TITLE
[NodeJS] [CSharp] - CSV / Arrays / Lists in URL's are not replaced correctly 

### ISSUE THREAD

**Issue by aschua** [Azure/autorest#900]
Hello everybody,

having a Java EE REST-Endpoint annotated like:

```java
  @com.my-domain.ess.interceptor.binding.ServiceOperation("query")
  @javax.ws.rs.GET
  @javax.ws.rs.Path("{parentId}/query")         
  @javax.ws.rs.Produces({javax.ws.rs.core.MediaType.APPLICATION_XML, javax.ws.rs.core.MediaType.APPLICATION_JSON})
  @io.swagger.annotations.ApiOperation(value="Wer suchet, der findet", nickname="MischtabellenQuery",
      authorizations = {
      @io.swagger.annotations.Authorization(
          value="oauth", 
          scopes = { @io.swagger.annotations.AuthorizationScope(scope = "ess", description = "OAuth-Authentifizierung f. ESS") }
          )
    }
  )

  @io.swagger.annotations.ApiResponses(value = 
  {
    @io.swagger.annotations.ApiResponse(code = 200, message = "OK", response=com.gfi.eva.serviceschicht.zentral.SchluesseltabellenEintragQueryResponse.class), 
  })                                  
  public javax.ws.rs.core.Response query(@javax.ws.rs.PathParam("parentId") java.util.List<String> parentIds) throws Exception
```

I'm getting this swagger:

```javascript
"/Services/Mischtabellen/{parentId}/query" : {
      "get" : {
        "tags" : [ "MischtabellenRessource" ],
        "summary" : "Wer suchet, der findet",
        "description" : "",
        "operationId" : "MischtabellenQuery",
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [ {
          "name" : "parentId",
          "in" : "path",
          "required" : true,
          "type" : "array",
          "items" : {
            "type" : "string"
          },
          "collectionFormat" : "csv"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/SchluesseltabellenEintragQueryResponse"
            }
          }
        },
        "security" : [ {
          "oauth" : [ "ess" ]
        } ]
      }
    }
```

The relevant part of the generated client is this:

```javascript
ESS.prototype.query = function (parentId, options, callback) {
  var client = this;
  if(!callback && typeof options === 'function') {
    callback = options;
    options = null;
  }
  if (!callback) {
    throw new Error('callback cannot be null.');
  }
  // Validate
  ...
  // Construct URL
  var requestUrl = this.baseUri +
                   '//Services/Mischtabellen/{parentId:commaSeparated}/query';
  requestUrl = requestUrl.replace('{parentId}', encodeURIComponent(parentId.toString()));
```
The parameter `parentId` is an array and got validated correctly. In the `requestUrl` the `{parentId:commaSeparated}` should be replaced by the array in `parentId`. But the call `requestUrl.replace()` tries to replace `{parentId}` instead of `{parentId:commaSeparated}`. Hence the replacement never happenes and the called URL is wrong.

Fixing the replacement to `{parentId:commaSeparated}` works as expected.

The problem occurs in the NodeJS and CSharp client in the same way.

Thanks!
Alex

**Comment by amarzavery** [comment]
@aschua - 

Let us assume that `var parentId = ['Foo', 'Bar', Baz'];`
How would you expect, the array value of `parentId` path parameter in this partial url `/Services/Mischtabellen/{parentId}/query`:

- as a literal array with square brackets `/Services/Mischtabellen/ ['Foo', 'Bar', Baz']/query`
- as a comma separated string `/Services/Mischtabellen/Foo,Bar,Baz/query`

I think the second option is the correct approach if the collection format is specified as csv and if the collection format is not specified then the first option looks correct.

@devigned @markcowl - Any thoughts?

Some SO links: 
- http://stackoverflow.com/questions/9623258/passing-an-array-or-list-to-pathvariable-spring-java
- http://stackoverflow.com/questions/4541338/how-to-construct-a-rest-api-that-takes-an-array-of-ids-for-the-resources

**Comment by aschua** [comment]
@amarzavery: We have misunterstood. You are right, the second approach is correct. My point is, the replacement doesn't work.

In the URL is `{parentId:commaSeparated}` included, but the generated code tries to replace `{parentId}`. As this pattern isn't found, the resulting URL is wrong.

**Comment by amarzavery** [comment]
@aschua - I am sorry for not putting all the information in my response. I understood the problem you posted and tried to solve the problem in my existing open PR #913. After making sure that the requestUrl.replace correctly appends the `:commaseparated` to the path parameter that has collection format specified as `csv`, I found out that the generated C# code serializes the path parameter into an array `[a,b,c]` instead of a comma separated string `a,b,c`.

This made me think of a broader question.
- Is it possible to send an array as a path parameter **without specifying any collection format** in a request url. Is this technically correct as a RESTful API?

Note: My question is about the scenario where someone wants to pass an array as a path parameter and the collection format is not specified.

**Comment by amarzavery** [comment]
@aschua - I got the answer to my question.
As per the [swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object), if a parameter of type array is specified for location other than body then the collectionFormat defaults to `"csv"`.

collectionFormat  string  Determines the format of the array if type array is used. Possible values are: • csv  - comma separated values  foo,bar . 
• ssv  - space separated values  foo bar . 
• tsv  - tab separated values  foo\tbar . 
• pipes  - pipe separated values  foo|bar . 
• multi  - corresponds to multiple parameter instances instead of multiple values for a single instance  foo=bar&foo=baz . This is valid only for parameters  in  "query" or "formData". 
Default value is  csv . 

Will update the PR accordingly.

**Comment by amarzavery** [comment]
@aschua - My current PR fixes this for C# and node.js.

**Comment by amarzavery** [comment]
@aschua - You can try tonight's nightly build `0.16.0-Nightly20160404` from [this feed](https://www.myget.org/F/autorest/api/v2) or generate after building from the master branch of this repo.

**Comment by aschua** [comment]
@amarzavery - I tried the nightly build and the problem is fixed. Thank you very much for the quick replies and the fix!
