### ISSUE TITLE
-useDateTimeOffset not listed in command line help

### ISSUE THREAD

**Issue by koolraap** [Azure/autorest#936]
The -UseDateTimeOffset parameter is not listed as a possible value on the command line. To reproduce open a cmd shell:

```
autorest.exe
```

Expected result: -UseDateTimeOffset is listed amongst options.

Actual result: -UseDateTimeOffset is not listed amongst options.

**Comment by amarzavery** [comment]
Thanks for reporting this. This will be fixed in the upcoming release.

**Comment by fearthecowboy** [comment]
@dsgouda 

This doesn't show up because we don't expose settings for individual generators.

What I'd like you to do is add support so that someone could use :

``` powershell
> AutoRest.exe -help -CodeGenerator Azure.Csharp
``` 
and it would spit out the same help PLUS the help for the specific generator .

(you'll need to load the plugin, get the `plugin.Settings` and pass that thru whatever generates the help.

G

**Comment by koolraap** [comment]
Add wildcard support for bonus points:

     > AutoRest.exe -help -CodeGenerator *
     > AutoRest.exe -help -cg *sharp*
